# Generated by Django 5.2.14 on 2026-06-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='source_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_role_assignments', to='core.proposal', verbose_name='来源提案'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='source_proposal_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_role_assignments', to='core.proposalexecution', verbose_name='来源提案执行'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='source_type',
            field=models.CharField(choices=[('direct', '直接任命'), ('proposal', '提案执行'), ('initialization', '初始化'), ('system', '系统产生')], default='direct', help_text='说明这条角色任命由直接任命、提案执行、初始化或系统规则产生。', max_length=32, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_tasks', to='core.proposal', verbose_name='来源提案'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_proposal_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_tasks', to='core.proposalexecution', verbose_name='来源提案执行'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('direct', '直接创建'), ('proposal', '提案执行'), ('plan', '计划派生'), ('simulation', '仿真产生'), ('system', '系统产生')], default='direct', help_text='说明任务由直接运营、提案执行、计划派生、仿真或系统规则产生。', max_length=32, verbose_name='来源类型'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['source_type'], name='core_role_a_source__b5d685_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['source_proposal'], name='core_role_a_source__794d43_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source_type'], name='core_task_source__728a63_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source_proposal'], name='core_task_source__c71fab_idx'),
        ),
    ]
