# Generated by Django 5.2.16 on 2026-08-20 05:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalproposal',
            name='frozen_approve_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='开始表决时从已发布规则版本冻结的赞成票门槛。', null=True, verbose_name='冻结通过阈值'),
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='frozen_minimum_participation',
            field=models.PositiveIntegerField(blank=True, help_text='开始表决时冻结的最低有效投票人数。', null=True, verbose_name='冻结最低参与数'),
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='frozen_reject_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='开始表决时从已发布规则版本冻结的反对票门槛。', null=True, verbose_name='冻结拒绝阈值'),
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='frozen_unresolved_outcome',
            field=models.CharField(blank=True, default='', help_text='截止时未达到通过或拒绝条件时采用 rejected 或 expired。', max_length=16, verbose_name='冻结未决处理'),
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='strategy_type',
            field=models.CharField(choices=[('approval_slots', '固定审批槽'), ('electorate', '版本化选民规则')], default='approval_slots', help_text='固定审批槽用于尚未迁移的既有审批；版本化选民规则用于统一表决。', max_length=24, verbose_name='决策策略'),
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='voting_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='表决截止时间'),
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='voting_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='表决开始时间'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='admission_proposal',
            field=models.OneToOneField(blank=True, help_text='由新统一提案系统创建的唯一准入提案；不保存旧提案兼容关系。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_application', to='core.approvalproposal', verbose_name='准入提案'),
        ),
        migrations.AlterField(
            model_name='approvalproposal',
            name='status',
            field=models.CharField(choices=[('draft', '草拟'), ('awaiting_policy', '等待政策配置'), ('submitted', '已提交'), ('voting', '表决中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('expired', '已过期'), ('cancelled', '已取消'), ('executed', '已执行'), ('execution_failed', '执行失败')], default='submitted', max_length=16, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ElectorateRuleTemplate',
            fields=[
                ('rule_code', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='规则代码')),
                ('proposal_type', models.CharField(help_text='稳定提案类型代码；规则不能被其他类型临时复用。', max_length=64, verbose_name='适用提案类型')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='可继续发布')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_electorate_rule_templates', to='core.member', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '选民规则模板',
                'verbose_name_plural': '选民规则模板',
                'db_table': 'core_electorate_rule_template',
            },
        ),
        migrations.CreateModel(
            name='ElectorateRuleVersion',
            fields=[
                ('rule_version_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='规则版本ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('selector_config', models.JSONField(help_text='仅保存通过服务端 schema 验证的 ALL、ANY、角色、派生状态、专业资格和排除条件。', verbose_name='选择器配置')),
                ('approve_threshold', models.PositiveIntegerField(verbose_name='通过阈值')),
                ('reject_threshold', models.PositiveIntegerField(verbose_name='拒绝阈值')),
                ('minimum_participation', models.PositiveIntegerField(default=0, verbose_name='最低参与数')),
                ('voting_duration_hours', models.PositiveIntegerField(verbose_name='表决期限小时数')),
                ('unresolved_outcome', models.CharField(choices=[('rejected', '拒绝'), ('expired', '过期')], max_length=16, verbose_name='未决处理')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_electorate_rule_versions', to='core.member', verbose_name='发布人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.electorateruletemplate', verbose_name='规则模板')),
            ],
            options={
                'verbose_name': '选民规则版本',
                'verbose_name_plural': '选民规则版本',
                'db_table': 'core_electorate_rule_version',
                'ordering': ['template_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='approvalproposal',
            name='electorate_rule_version',
            field=models.ForeignKey(blank=True, help_text='统一表决开始后不可替换的已发布规则版本。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='core.electorateruleversion', verbose_name='选民规则版本'),
        ),
        migrations.CreateModel(
            name='ProposalBallot',
            fields=[
                ('ballot_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='票据ID')),
                ('revision', models.PositiveIntegerField(verbose_name='修订序号')),
                ('choice', models.CharField(choices=[('approve', '赞成'), ('reject', '反对'), ('abstain', '弃权')], max_length=16, verbose_name='选择')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='core.approvalproposal', verbose_name='提案')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_ballots', to='core.member', verbose_name='投票人')),
            ],
            options={
                'verbose_name': '提案票据',
                'verbose_name_plural': '提案票据',
                'db_table': 'core_proposal_ballot',
                'ordering': ['proposal_id', 'voter_id', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='ProposalElectorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_evidence', models.JSONField(blank=True, default=dict, help_text='生成快照时满足规则的公开安全依据。', verbose_name='资格证据')),
                ('snapshotted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='快照时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_elector_snapshots', to='core.member', verbose_name='成员')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elector_snapshots', to='core.approvalproposal', verbose_name='提案')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elector_snapshots', to='core.electorateruleversion', verbose_name='规则版本')),
            ],
            options={
                'verbose_name': '提案选民快照',
                'verbose_name_plural': '提案选民快照',
                'db_table': 'core_proposal_elector_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ProposalExecutionRecord',
            fields=[
                ('execution_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='执行ID')),
                ('idempotency_key', models.CharField(max_length=191, unique=True, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('running', '执行中'), ('succeeded', '成功'), ('failed', '失败')], max_length=16, verbose_name='状态')),
                ('public_error_code', models.CharField(blank=True, help_text='可安全展示的稳定错误代码，不保存异常堆栈。', max_length=64, verbose_name='公开错误代码')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='适配器返回的公开安全幂等结果。', verbose_name='执行结果')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_executions', to='core.member', verbose_name='执行人')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_record', to='core.approvalproposal', verbose_name='提案')),
            ],
            options={
                'verbose_name': '提案执行记录',
                'verbose_name_plural': '提案执行记录',
                'db_table': 'core_proposal_execution_record',
            },
        ),
        migrations.CreateModel(
            name='ProposalResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', '通过'), ('rejected', '拒绝'), ('expired', '过期')], max_length=16, verbose_name='结果')),
                ('reason_code', models.CharField(max_length=64, verbose_name='判定代码')),
                ('evidence', models.JSONField(help_text='保存选民数、有效参与数、各选项票数和采用的冻结阈值。', verbose_name='判定证据')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='判定时间')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='core.approvalproposal', verbose_name='提案')),
            ],
            options={
                'verbose_name': '提案判定证据',
                'verbose_name_plural': '提案判定证据',
                'db_table': 'core_proposal_resolution',
            },
        ),
        migrations.AddIndex(
            model_name='electorateruletemplate',
            index=models.Index(fields=['proposal_type', 'is_active'], name='core_electo_proposa_dca311_idx'),
        ),
        migrations.AddConstraint(
            model_name='electorateruleversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_electorate_rule_version'),
        ),
        migrations.AddIndex(
            model_name='proposalballot',
            index=models.Index(fields=['proposal', 'voter', '-revision'], name='core_propos_proposa_e9ba62_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalballot',
            constraint=models.UniqueConstraint(fields=('proposal', 'voter', 'revision'), name='unique_proposal_ballot_revision'),
        ),
        migrations.AddIndex(
            model_name='proposalelectorsnapshot',
            index=models.Index(fields=['proposal', 'member'], name='core_propos_proposa_861185_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalelectorsnapshot',
            constraint=models.UniqueConstraint(fields=('proposal', 'member'), name='unique_proposal_elector_snapshot'),
        ),
    ]
