# Generated by Django 5.2.16 on 2026-08-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_approvalproposal_frozen_approve_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('deliberator_exam_question_changed', '执衡者题库已变更'), ('deliberator_exam_policy_changed', '执衡者考试政策已变更'), ('credential_granted', '凭证已发放'), ('expense_claim_submitted', '报销申请已提交'), ('expense_claim_reviewed', '报销申请已审核'), ('expense_claim_paid', '报销已付款'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('event_feedback_submitted', '事件反馈已提交'), ('event_feedback_verification_started', '事件反馈已开始核实'), ('event_feedback_response_requested', '事件反馈已请求回应'), ('event_feedback_responded', '事件反馈已回应'), ('event_feedback_concluded', '事件反馈已形成结论'), ('event_feedback_closed', '事件反馈已结束'), ('event_feedback_withdrawn', '事件反馈已撤回'), ('resource_adjusted', '资源已调整'), ('supplier_offer_submitted', '供给报价已提交'), ('supplier_offer_accepted', '供给报价已采纳'), ('supplier_offer_rejected', '供给报价已拒绝'), ('supplier_offer_receipt_accepted', '供给报价验收通过'), ('supplier_offer_receipt_rejected', '供给报价验收失败'), ('supplier_offer_completed', '供给报价已完成'), ('approval_proposal_submitted', '审批提案已提交'), ('approval_proposal_approved', '审批提案已通过'), ('approval_proposal_rejected', '审批提案已拒绝'), ('approval_proposal_executed', '审批提案已执行'), ('approval_proposal_cancelled', '审批提案已取消'), ('electorate_rule_published', '选民规则已发布'), ('proposal_voting_started', '提案表决已开始'), ('proposal_ballot_cast', '提案票据已提交'), ('proposal_expired', '提案已过期'), ('proposal_execution_failed', '提案执行失败'), ('procurement_challenge_submitted', '采购质疑已提交'), ('procurement_challenge_reviewed', '采购质疑已处理'), ('risk_alert_triggered', '风险告警已触发'), ('risk_alert_acknowledged', '风险告警已确认'), ('risk_alert_resolved', '风险告警已解除'), ('risk_alert_dismissed', '风险告警已忽略'), ('risk_rule_updated', '风险规则已更新'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
    ]
