# Generated by Django 5.2.14 on 2026-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roleassignment_source_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
    ]
