# Generated by Django 5.2.14 on 2026-07-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_systemevent_event_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simulationrun',
            name='core_simrun_world_status_idx',
        ),
        migrations.RemoveField(
            model_name='simulationrun',
            name='world',
        ),
        migrations.DeleteModel(
            name='SimulationWorld',
        ),
    ]
