# Generated by Django 5.2.14 on 2026-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systemevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationfailure',
            name='failure_type',
            field=models.CharField(choices=[('budget_unrealistic', '预算不合理'), ('labor_shortage', '人力不足'), ('skill_shortage', '技能不足'), ('resource_shortage', '资源不足'), ('dependency_unmet', '前置条件未满足'), ('personnel_issue', '人员状态问题'), ('execution_issue', '执行过程问题'), ('responsibility_closure_missing', '责任闭环缺失')], max_length=32, verbose_name='失败类型'),
        ),
    ]
