# Generated by Django 5.2.14 on 2026-07-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_simulationfailure_failure_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSnapshot',
            fields=[
                ('snapshot_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='仿真快照ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('source_world_id', models.CharField(max_length=64, verbose_name='来源世界ID')),
                ('source_world_type', models.CharField(max_length=24, verbose_name='来源世界类型')),
                ('source_database_alias', models.CharField(max_length=64, verbose_name='来源数据库别名')),
                ('source_database_name', models.CharField(blank=True, max_length=128, verbose_name='来源数据库名称')),
                ('source_run_id', models.CharField(max_length=96, verbose_name='来源仿真运行ID')),
                ('plan_revision_id', models.CharField(blank=True, max_length=64, verbose_name='计划版本ID')),
                ('run_status', models.CharField(max_length=16, verbose_name='运行状态')),
                ('failure_type', models.CharField(blank=True, max_length=64, verbose_name='失败类型')),
                ('failure_title', models.CharField(blank=True, max_length=255, verbose_name='失败标题')),
                ('snapshot_schema_version', models.PositiveIntegerField(default=1, verbose_name='快照结构版本')),
                ('status', models.CharField(choices=[('archived', '已归档')], default='archived', max_length=16, verbose_name='状态')),
                ('raw_archive_path', models.CharField(max_length=512, verbose_name='原始归档路径')),
                ('raw_archive_hash', models.CharField(max_length=64, verbose_name='原始归档哈希')),
                ('report_path', models.CharField(blank=True, max_length=512, verbose_name='报告路径')),
                ('raw_table_counts', models.JSONField(blank=True, default=dict, verbose_name='原始表计数')),
                ('normalized_summary', models.JSONField(blank=True, default=dict, verbose_name='标准化摘要')),
                ('code_version', models.CharField(blank=True, max_length=64, verbose_name='代码版本')),
                ('archived_at', models.DateTimeField(verbose_name='归档时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '仿真快照',
                'verbose_name_plural': '仿真快照',
                'db_table': 'core_simulation_snapshot',
                'ordering': ['-archived_at', 'snapshot_id'],
                'indexes': [models.Index(fields=['source_world_id', 'archived_at'], name='core_simula_source__e8867a_idx'), models.Index(fields=['run_status'], name='core_simula_run_sta_21ff70_idx'), models.Index(fields=['failure_type'], name='core_simula_failure_f9b118_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_world_id', 'source_run_id'), name='unique_snapshot_source_run')],
            },
        ),
        migrations.CreateModel(
            name='SimulationSnapshotItem',
            fields=[
                ('item_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='快照明细ID')),
                ('item_type', models.CharField(choices=[('summary', '摘要'), ('run', '仿真运行'), ('node_state', '节点状态'), ('turn', '推演日志'), ('failure', '失败记录'), ('event', '观察事件'), ('proposal', '修订建议'), ('change_set', '变更集'), ('change_operation', '变更操作')], max_length=32, verbose_name='明细类型')),
                ('source_model', models.CharField(max_length=96, verbose_name='来源模型')),
                ('source_pk', models.CharField(blank=True, max_length=128, verbose_name='来源主键')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='标准化内容')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.simulationsnapshot', verbose_name='仿真快照')),
            ],
            options={
                'verbose_name': '仿真快照明细',
                'verbose_name_plural': '仿真快照明细',
                'db_table': 'core_simulation_snapshot_item',
                'ordering': ['snapshot', 'sort_order', 'item_id'],
                'indexes': [models.Index(fields=['snapshot', 'item_type'], name='core_simula_snapsho_be15b8_idx'), models.Index(fields=['source_model', 'source_pk'], name='core_simula_source__346f51_idx'), models.Index(fields=['item_type'], name='core_simula_item_ty_4d6007_idx')],
            },
        ),
    ]
