# Generated by Django 5.2.14 on 2026-07-03 14:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_snapshot_dispositions(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return
    SimulationSnapshot = apps.get_model("core", "SimulationSnapshot")
    SimulationRunDisposition = apps.get_model("core", "SimulationRunDisposition")
    snapshots_by_world = {}
    for snapshot in SimulationSnapshot.objects.order_by("source_world_id", "archived_at", "snapshot_id"):
        snapshots_by_world.setdefault(snapshot.source_world_id, []).append(snapshot)

    for source_world_id, snapshots in snapshots_by_world.items():
        for index, snapshot in enumerate(snapshots, start=1):
            normalized_summary = snapshot.normalized_summary if isinstance(snapshot.normalized_summary, dict) else {}
            failures = normalized_summary.get("failures") if isinstance(normalized_summary.get("failures"), list) else []
            first_failure = failures[0] if failures and isinstance(failures[0], dict) else {}
            failure_metadata = first_failure.get("metadata") if isinstance(first_failure.get("metadata"), dict) else {}
            scenario = str(failure_metadata.get("scenario") or "")

            snapshot.simulation_round = snapshot.simulation_round or index
            snapshot.scenario = snapshot.scenario or scenario
            snapshot.public_title = snapshot.public_title or snapshot.title
            snapshot.public_summary = snapshot.public_summary or snapshot.failure_title
            snapshot.publication_status = snapshot.publication_status or "public"
            snapshot.save(
                update_fields=[
                    "simulation_round",
                    "scenario",
                    "public_title",
                    "public_summary",
                    "publication_status",
                ]
            )

            SimulationRunDisposition.objects.get_or_create(
                source_world_id=source_world_id,
                source_run_id=snapshot.source_run_id,
                defaults={
                    "disposition_id": f"sim-disposition-{snapshot.snapshot_id}",
                    "source_world_type": snapshot.source_world_type,
                    "source_database_alias": snapshot.source_database_alias,
                    "source_database_name": snapshot.source_database_name,
                    "run_status": snapshot.run_status,
                    "run_started_at": None,
                    "run_ended_at": None,
                    "simulation_round": snapshot.simulation_round or index,
                    "scenario": snapshot.scenario,
                    "disposition": "archived",
                    "reason": "历史快照迁移为正式仿真处置记录。",
                    "decided_by": "migration:core.0008",
                    "decided_at": snapshot.archived_at,
                    "snapshot": snapshot,
                    "metadata": {"backfilled_from_snapshot": True},
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_simulationsnapshot_simulationsnapshotitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRunDisposition',
            fields=[
                ('disposition_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='处置ID')),
                ('source_world_id', models.CharField(max_length=64, verbose_name='来源世界ID')),
                ('source_world_type', models.CharField(max_length=24, verbose_name='来源世界类型')),
                ('source_database_alias', models.CharField(max_length=64, verbose_name='来源数据库别名')),
                ('source_database_name', models.CharField(blank=True, max_length=128, verbose_name='来源数据库名称')),
                ('source_run_id', models.CharField(max_length=96, verbose_name='来源仿真运行ID')),
                ('run_status', models.CharField(max_length=16, verbose_name='运行状态')),
                ('run_started_at', models.DateTimeField(blank=True, null=True, verbose_name='运行开始时间')),
                ('run_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='运行结束时间')),
                ('simulation_round', models.PositiveIntegerField(verbose_name='仿真轮次')),
                ('scenario', models.CharField(blank=True, max_length=64, verbose_name='仿真场景')),
                ('disposition', models.CharField(choices=[('archived', '已归档'), ('discarded', '放弃归档')], max_length=16, verbose_name='处置结果')),
                ('reason', models.TextField(verbose_name='处置原因')),
                ('decided_by', models.CharField(blank=True, max_length=128, verbose_name='处置人')),
                ('decided_at', models.DateTimeField(verbose_name='处置时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '仿真运行处置记录',
                'verbose_name_plural': '仿真运行处置记录',
                'db_table': 'core_simulation_run_disposition',
                'ordering': ['-decided_at', 'source_world_id', 'simulation_round'],
            },
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='hypothesis',
            field=models.TextField(blank=True, verbose_name='仿真假设'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='next_run_basis',
            field=models.TextField(blank=True, verbose_name='下一轮依据'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='parameter_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='参数摘要'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='public_summary',
            field=models.TextField(blank=True, verbose_name='公开摘要'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='public_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='公开标题'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='publication_status',
            field=models.CharField(choices=[('public', '公开展示'), ('internal', '内部复盘'), ('hidden', '隐藏')], default='public', max_length=16, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='仿真目的'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='review_conclusion',
            field=models.TextField(blank=True, verbose_name='复盘结论'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='scenario',
            field=models.CharField(blank=True, max_length=64, verbose_name='仿真场景'),
        ),
        migrations.AddField(
            model_name='simulationsnapshot',
            name='simulation_round',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='仿真轮次'),
        ),
        migrations.AddIndex(
            model_name='simulationsnapshot',
            index=models.Index(fields=['source_world_id', 'simulation_round'], name='core_simula_source__3e5400_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsnapshot',
            index=models.Index(fields=['scenario'], name='core_simula_scenari_6af4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsnapshot',
            index=models.Index(fields=['publication_status'], name='core_simula_publica_138429_idx'),
        ),
        migrations.AddField(
            model_name='simulationrundisposition',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='core.simulationsnapshot', verbose_name='关联快照'),
        ),
        migrations.RunPython(backfill_snapshot_dispositions, noop_reverse),
        migrations.AddIndex(
            model_name='simulationrundisposition',
            index=models.Index(fields=['source_world_id', 'simulation_round'], name='core_simula_source__a1d735_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrundisposition',
            index=models.Index(fields=['source_world_id', 'source_run_id'], name='core_simula_source__359fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrundisposition',
            index=models.Index(fields=['disposition'], name='core_simula_disposi_13679e_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrundisposition',
            index=models.Index(fields=['scenario'], name='core_simula_scenari_003ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrundisposition',
            index=models.Index(fields=['decided_at'], name='core_simula_decided_3cfd95_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationrundisposition',
            constraint=models.UniqueConstraint(fields=('source_world_id', 'source_run_id'), name='unique_simulation_run_disposition'),
        ),
    ]
