# Generated by Django 5.2.14 on 2026-07-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_simulationrundisposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('application_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='成员报名ID')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='报名人名称')),
                ('contact', models.CharField(max_length=255, verbose_name='联系方式')),
                ('motivation', models.TextField(verbose_name='报名动机')),
                ('availability_hours_per_week', models.PositiveIntegerField(help_text='报名人自述的稳定可投入时间。', verbose_name='每周可投入小时')),
                ('capability_scores', models.JSONField(blank=True, default=dict, help_text='报名人自述能力，第一版用 key/value 结构保存。', verbose_name='能力自评')),
                ('can_issue_responsibility_documents', models.BooleanField(default=False, help_text='成员报名中通常为否；如果个人具备签字、盖章或合同责任能力，可标记为是。', verbose_name='可出具责任文件')),
                ('document_authority_domains', models.JSONField(blank=True, default=list, help_text='可出具或承担责任的文件领域，例如结构安全、电气并网。', verbose_name='责任文件领域')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('under_review', '审核中'), ('candidate', '进入候选池'), ('standby', '备用'), ('rejected', '已拒绝'), ('withdrew', '已退出')], default='submitted', max_length=32, verbose_name='状态')),
                ('requested_member_no', models.CharField(blank=True, max_length=64, verbose_name='期望成员编号')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('linked_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_applications', to='core.member', verbose_name='关联成员')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_member_applications', to='core.member', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '成员报名',
                'verbose_name_plural': '成员报名',
                'db_table': 'core_member_application',
                'ordering': ['-submitted_at', 'application_id'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='core_member_status_24270b_idx'), models.Index(fields=['requested_member_no'], name='core_member_request_4ccd3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('application_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='合作方报名ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='合作方名称')),
                ('contact_name', models.CharField(max_length=255, verbose_name='联系人')),
                ('contact', models.CharField(max_length=255, verbose_name='联系方式')),
                ('service_domains', models.JSONField(blank=True, default=list, help_text='合作方可提供的服务、能力或资质领域。', verbose_name='服务能力')),
                ('can_issue_responsibility_documents', models.BooleanField(default=False, help_text='是否能出具可归档、可追责、可作为决策依据的书面文件。', verbose_name='可出具责任文件')),
                ('responsibility_document_domains', models.JSONField(blank=True, default=list, help_text='可签署或盖章承担责任的文件领域。', verbose_name='责任文件领域')),
                ('qualification_summary', models.TextField(blank=True, verbose_name='资质说明')),
                ('quote_summary', models.TextField(blank=True, verbose_name='报价说明')),
                ('service_area', models.CharField(blank=True, max_length=255, verbose_name='服务地区')),
                ('delivery_cycle_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='交付周期天数')),
                ('constraints', models.TextField(blank=True, verbose_name='限制条件')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('under_review', '审核中'), ('qualified', '可合作'), ('standby', '备用'), ('rejected', '已拒绝'), ('withdrew', '已退出')], default='submitted', max_length=32, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_partner_applications', to='core.member', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '合作方报名',
                'verbose_name_plural': '合作方报名',
                'db_table': 'core_partner_application',
                'ordering': ['-submitted_at', 'application_id'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='core_partne_status_a6e56a_idx'), models.Index(fields=['can_issue_responsibility_documents'], name='core_partne_can_iss_a0518c_idx')],
            },
        ),
    ]
