# Generated by Django 5.2.14 on 2026-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_systemevent_event_type_memberapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrun',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('running', '运行中'), ('failed', '已失败'), ('completed', '已完成'), ('paused', '已暂停'), ('aborted', '已中止')], default='draft', max_length=16, verbose_name='状态'),
        ),
    ]
