# Generated by Django 5.2.14 on 2026-07-05 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_simulationrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequirement',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='当需求对应当前库存台账中的某类资源时填写，用于计算库存缺口和匹配供应商报价。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_requirements', to='core.resource', verbose_name='对应资源'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('facility', '设施'), ('room', '房间'), ('system', '系统'), ('material', '材料'), ('equipment', '设备'), ('grain', '粮食'), ('vegetables', '蔬菜'), ('water', '水'), ('electricity', '电'), ('cash', '现金'), ('medicine', '药品'), ('tools', '工具'), ('cleaning_supplies', '清洁用品'), ('beds', '床位'), ('warehouse_capacity', '仓库容量')], max_length=32, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(choices=[('kg', '千克'), ('bag', '袋'), ('liter', '升'), ('kwh', '千瓦时'), ('yuan', '元'), ('count', '个'), ('slot', '位'), ('cubic_meter', '立方米')], max_length=16, verbose_name='单位'),
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('quote_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='报价ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='单价')),
                ('currency', models.CharField(default='CNY', max_length=16, verbose_name='币种')),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='可供数量')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='最小起订量')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='交付周期天数')),
                ('quality_grade', models.CharField(choices=[('unknown', '未评估'), ('low_risk', '低风险'), ('standard', '标准'), ('high_quality', '高质量'), ('risky', '高风险')], default='unknown', max_length=32, verbose_name='质量评估')),
                ('quality_summary', models.TextField(blank=True, verbose_name='质量说明')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='有效开始')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效截止')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('expired', '已过期'), ('rejected', '已拒绝')], default='active', max_length=32, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('partner_application', models.ForeignKey(help_text='报价来源。第一版直接引用合作方报名，后续可沉淀为供应商档案。', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='core.partnerapplication', verbose_name='合作方报名')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='core.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '供应商报价',
                'verbose_name_plural': '供应商报价',
                'db_table': 'core_supplier_quote',
                'ordering': ['resource', 'unit_price', 'lead_time_days', 'quote_id'],
                'indexes': [models.Index(fields=['resource', 'status'], name='core_suppli_resourc_fed07d_idx'), models.Index(fields=['partner_application', 'status'], name='core_suppli_partner_1af751_idx'), models.Index(fields=['valid_until'], name='core_suppli_valid_u_33d929_idx')],
            },
        ),
    ]
