# Generated by Django 5.2.14 on 2026-07-05 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_planrequirement_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=96, primary_key=True, serialize=False, verbose_name='库存流水ID')),
                ('transaction_type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('stocktake_adjustment', '盘点调整'), ('loss', '损耗'), ('scrap', '报废'), ('transfer', '调拨'), ('manual_adjustment', '人工调整')], max_length=32, verbose_name='流水类型')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='变动数量')),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='变动前库存')),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='变动后库存')),
                ('reason', models.TextField(verbose_name='原因')),
                ('operator', models.JSONField(blank=True, default=dict, verbose_name='操作人')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('related_supplier_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_transactions', to='core.supplierquote', verbose_name='关联供应商报价')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_transactions', to='core.task', verbose_name='关联任务')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.resource', verbose_name='资源')),
                ('system_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_transactions', to='core.systemevent', verbose_name='统一事件账本记录')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'core_resource_transaction',
                'ordering': ['occurred_at', 'transaction_id'],
                'indexes': [models.Index(fields=['resource', 'occurred_at'], name='core_resour_resourc_39b186_idx'), models.Index(fields=['transaction_type'], name='core_resour_transac_a3081b_idx'), models.Index(fields=['system_event'], name='core_resour_system__4667a5_idx')],
            },
        ),
    ]
