# Generated by Django 5.2.15 on 2026-07-12 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_resourcetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='account_user',
            field=models.ForeignKey(blank=True, help_text='成员报名时创建的登录账号；审核通过后绑定到成员身份。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_applications', to=settings.AUTH_USER_MODEL, verbose_name='报名账号'),
        ),
    ]
