# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_memberapplication_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "活跃"),
                    ("pending_training", "待培训"),
                    ("pending_review", "待审核"),
                    ("admitted", "已接纳"),
                    ("application_rejected", "报名未通过"),
                    ("suspended", "已暂停"),
                    ("exited", "已退出"),
                ],
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="memberapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "已提交"),
                    ("under_review", "审核中"),
                    ("candidate", "进入候选池"),
                    ("admitted", "已接纳"),
                    ("standby", "备用"),
                    ("rejected", "已拒绝"),
                    ("withdrew", "已退出"),
                ],
                default="submitted",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="memberapplication",
            name="availability_hours_per_week",
            field=models.PositiveIntegerField(
                default=0,
                help_text="历史兼容字段；当前报名表以 availability_slots 表达可参与时段。",
                verbose_name="每周可投入小时",
            ),
        ),
        migrations.AlterField(
            model_name="memberapplication",
            name="account_user",
            field=models.ForeignKey(
                blank=True,
                help_text="成员报名时创建或复用的登录账号；提交后立即绑定到最小权限成员身份。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="报名账号",
            ),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="role_gap",
            field=models.CharField(
                blank=True,
                default="",
                help_text="报名人选择的当前社区角色缺口，例如 settled_resident 或 developer_ai_engineer。",
                max_length=64,
                verbose_name="意向角色缺口",
            ),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="availability_slots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="当前报名表的多选时段，例如 any_time、off_hours、weekend。",
                verbose_name="可参与时段",
            ),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="dynamic_answers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="报名表中会随业务调整的 textarea 问答数组，元素包含 key、label、type、answer。",
                verbose_name="动态问答",
            ),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="frozen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="报名提交并二次确认的时间；业务入口不提供提交后的撤回或修改。",
                null=True,
                verbose_name="提交确认时间",
            ),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="admission_proposal",
            field=models.ForeignKey(
                blank=True,
                help_text="用于接纳该报名成员的治理提案；通过后仍需显式执行。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_admission_applications",
                to="core.proposal",
                verbose_name="准入提案",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_type",
            field=models.CharField(
                choices=[
                    ("member_admission", "成员准入"),
                    ("role_appointment", "角色任命"),
                    ("role_revocation", "角色卸任"),
                    ("rule", "规则"),
                    ("policy", "政策"),
                    ("budget", "预算"),
                    ("project", "项目"),
                    ("statement", "声明"),
                ],
                max_length=32,
                verbose_name="提案类型",
            ),
        ),
        migrations.AlterField(
            model_name="proposalexecution",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("admit_member_application", "接纳成员报名"),
                    ("create_role_assignment", "创建角色任命"),
                    ("revoke_role_assignment", "撤销角色任命"),
                    ("create_rule", "创建规则"),
                    ("create_policy", "创建政策"),
                    ("record_statement", "记录声明"),
                    ("manual", "人工处理"),
                ],
                max_length=64,
                verbose_name="执行动作",
            ),
        ),
    ]
