# Generated by Django 5.2.15 on 2026-07-14 10:47

import django.db.models.deletion
from django.db import migrations, models


def migrate_application_statuses(apps, schema_editor):
    """Map old MemberApplication statuses to the new proposal-driven choices.

    under_review  -> admission_voting
    candidate     -> admission_voting
    standby       -> admission_voting
    submitted / admitted / rejected / withdrew are unchanged.

    Uses schema_editor.connection.alias so the update targets the same
    world database that this migration is being applied to, not the
    default router's implicit destination.
    """
    db_alias = schema_editor.connection.alias
    MemberApplication = apps.get_model("core", "MemberApplication")
    MemberApplication.objects.using(db_alias).filter(
        status__in=["under_review", "candidate", "standby"]
    ).update(status="admission_voting")


def migrate_metadata_keys(apps, schema_editor):
    """Rename old review metadata keys to the new decision keys.

    metadata.review_note    -> metadata.decision_note  (pop old key)
    metadata.reviewed_by    -> metadata.decided_by_display (pop old key)

    If the new key already exists, it is preserved; the old key is
    always removed regardless.  Only records with non-empty metadata
    are scanned.  Uses the migration's target database alias.
    """
    db_alias = schema_editor.connection.alias
    MemberApplication = apps.get_model("core", "MemberApplication")
    for app in MemberApplication.objects.using(db_alias).exclude(metadata={}):
        meta = dict(app.metadata or {})
        changed = False
        if "review_note" in meta:
            if "decision_note" not in meta:
                meta["decision_note"] = meta["review_note"]
            del meta["review_note"]
            changed = True
        if "reviewed_by" in meta:
            if "decided_by_display" not in meta:
                meta["decided_by_display"] = meta["reviewed_by"]
            del meta["reviewed_by"]
            changed = True
        if changed:
            app.metadata = meta
            app.save(using=db_alias, update_fields=["metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_member_application_registration_flow"),
    ]

    operations = [
        # 1. Rename reviewed fields to their new proposal-decision semantics.
        migrations.RenameField(
            model_name="memberapplication",
            old_name="reviewed_at",
            new_name="decided_at",
        ),
        migrations.RenameField(
            model_name="memberapplication",
            old_name="reviewed_by",
            new_name="decided_by",
        ),
        # 1b. Apply the new field attributes (help_text, related_name) that
        #     RenameField doesn't carry forward from the model definition.
        migrations.AlterField(
            model_name="memberapplication",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="执行准入提案或拒绝的治理成员；不再表示单人审核。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decided_member_applications",
                to="core.member",
                verbose_name="决议人",
            ),
        ),
        migrations.AlterField(
            model_name="memberapplication",
            name="decided_at",
            field=models.DateTimeField(
                blank=True,
                help_text="准入执行或拒绝的时间。",
                null=True,
                verbose_name="决议时间",
            ),
        ),
        # 2. Update status choices — removes candidate / standby, renames
        #    under_review -> admission_voting.
        migrations.AlterField(
            model_name="memberapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "已提交"),
                    ("admission_voting", "准入表决中"),
                    ("admitted", "已接纳"),
                    ("rejected", "已拒绝"),
                    ("withdrew", "已退出"),
                ],
                default="submitted",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        # 3. Data migration: map old status values that no longer exist.
        migrations.RunPython(
            code=migrate_application_statuses,
            reverse_code=migrations.RunPython.noop,
        ),
        # 4. Data migration: rename metadata review_* keys to decision_* keys.
        migrations.RunPython(
            code=migrate_metadata_keys,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
