# Generated by Django 5.2.16 on 2026-07-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_memberapplication_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(blank=True, help_text='公开显示名，不等同证件实名。为空时回落至 Member.display_name。', max_length=255, verbose_name='公开姓名')),
                ('avatar_url', models.URLField(blank=True, help_text='公开头像地址，使用 URL 而非上传文件。', max_length=1000, verbose_name='公开头像URL')),
                ('bio', models.TextField(blank=True, help_text='可选的公开自我介绍，不包含联系方式等隐私信息。', verbose_name='公开简介')),
                ('is_visible', models.BooleanField(default=True, help_text='关闭后公开主页只显示 display_name 回落信息。', verbose_name='公开展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='core.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '成员公开资料',
                'verbose_name_plural': '成员公开资料',
                'db_table': 'core_member_public_profile',
                'indexes': [models.Index(fields=['is_visible'], name='core_member_is_visi_32586c_idx'), models.Index(fields=['public_name'], name='core_member_public__b683d2_idx')],
            },
        ),
    ]
