# Generated by Django 5.2.16 on 2026-07-18 14:29

import core.models.credentials
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_memberpublicprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text='稳定的业务 ID，例如 credential-template-formal-member-number。', max_length=128, unique=True, verbose_name='模板 ID')),
                ('code', models.CharField(help_text='程序内唯一编码，例如 formal_member_number。', max_length=64, unique=True, verbose_name='凭证编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('credential_type', models.CharField(choices=[('formal_number', '正式成员编号'), ('badge', '勋章'), ('certificate', '证书'), ('nft_placeholder', 'NFT占位')], max_length=32, verbose_name='凭证类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '已归档')], default='active', max_length=32, verbose_name='状态')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('internal', '内部')], default='public', max_length=32, verbose_name='可见性')),
                ('icon_url', models.URLField(blank=True, verbose_name='图标 URL')),
                ('display_order', models.IntegerField(default=100, verbose_name='展示顺序')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '凭证模板',
                'verbose_name_plural': '凭证模板',
                'ordering': ('display_order', 'code'),
            },
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('credential_granted', '凭证已发放'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='CredentialGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.CharField(default=core.models.credentials.generate_credential_grant_id, help_text='业务 ID，自动生成。', max_length=96, unique=True, verbose_name='发放 ID')),
                ('serial_no', models.PositiveIntegerField(blank=True, help_text='递增序列号，同一模板内唯一（如正式成员编号 1,2,3…）。', null=True, verbose_name='序列号')),
                ('display_no', models.CharField(blank=True, help_text='对外展示编号，例如 #1 或 #0001。', max_length=32, verbose_name='展示编号')),
                ('title', models.CharField(blank=True, help_text='默认为模板名称；可单独覆写。', max_length=255, verbose_name='标题')),
                ('status', models.CharField(choices=[('active', '活跃'), ('revoked', '已撤销'), ('archived', '已归档')], default='active', max_length=32, verbose_name='状态')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发放时间')),
                ('source_type', models.CharField(choices=[('system', '系统'), ('proposal_execution', '提案执行'), ('manual', '手动'), ('earned', '自动获得')], default='system', help_text='记录该凭证的授予来源。', max_length=32, verbose_name='来源类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='core.member', verbose_name='发放人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_grants', to='core.member', verbose_name='成员')),
                ('source_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credential_grants', to='core.proposal', verbose_name='来源提案')),
                ('source_proposal_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credential_grants', to='core.proposalexecution', verbose_name='来源提案执行')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='core.credentialtemplate', verbose_name='凭证模板')),
            ],
            options={
                'verbose_name': '凭证发放',
                'verbose_name_plural': '凭证发放',
                'ordering': ('template', 'serial_no'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_no__isnull', False)), fields=('template', 'serial_no'), name='unique_template_serial_no'), models.UniqueConstraint(condition=models.Q(('display_no', ''), _negated=True), fields=('template', 'display_no'), name='unique_template_display_no')],
            },
        ),
    ]
