# Generated by Django 5.2.16 on 2026-07-19 07:23

import core.models.feedback
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_credentialtemplate_alter_systemevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(default=core.models.feedback._generate_feedback_id, help_text='稳定的业务 ID。', max_length=64, unique=True, verbose_name='反馈 ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('category', models.CharField(choices=[('question', '问题'), ('suggestion', '建议'), ('concern', '担忧/质疑'), ('proposal_seed', '提案种子'), ('other', '其他')], default='other', max_length=32, verbose_name='类别')),
                ('body', models.TextField(help_text='反馈的详细内容，纯文本。', verbose_name='正文')),
                ('status', models.CharField(choices=[('open', '待回应'), ('acknowledged', '已看到'), ('answered', '已回应'), ('linked', '已转入治理流程'), ('closed', '已关闭'), ('hidden', '已隐藏')], default='open', help_text='反馈的当前处理状态。', max_length=32, verbose_name='状态')),
                ('official_response', models.TextField(blank=True, help_text='治理成员的公开回应。', verbose_name='官方回应')),
                ('responded_at', models.DateTimeField(blank=True, help_text='最近一次回应的发生时间。', null=True, verbose_name='回应时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author_member', models.ForeignKey(help_text='提出反馈的注册成员。', on_delete=django.db.models.deletion.PROTECT, related_name='community_feedbacks', to='core.member', verbose_name='作者')),
                ('linked_proposal', models.ForeignKey(blank=True, help_text='由此反馈转入的正式治理提案。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_feedbacks', to='core.proposal', verbose_name='关联提案')),
                ('responded_by', models.ForeignKey(blank=True, help_text='最近回应该反馈的治理成员。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_community_feedbacks', to='core.member', verbose_name='回应人')),
            ],
            options={
                'verbose_name': '社区反馈',
                'verbose_name_plural': '社区反馈',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
