# Generated by Django 5.2.16 on 2026-07-19 11:35

import core.models.finance
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_communityfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(default=core.models.finance._new_claim_id, help_text='稳定的业务 ID。', max_length=64, unique=True, verbose_name='报销 ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('description', models.TextField(blank=True, help_text='描述这笔支出的用途和背景。', verbose_name='支出说明')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='货币')),
                ('expense_date', models.DateField(verbose_name='支出日期')),
                ('vendor', models.CharField(blank=True, help_text='供应商或收款方名称。', max_length=255, verbose_name='收款方')),
                ('category', models.CharField(choices=[('server', '服务器'), ('ai_usage', 'AI 使用费'), ('software', '软件'), ('operations', '运营支出'), ('other', '其他')], default='other', max_length=32, verbose_name='类别')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('under_review', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('paid', '已付款'), ('withdrawn', '已撤回')], default='submitted', max_length=32, verbose_name='状态')),
                ('public_note', models.TextField(blank=True, help_text='可在公开页面展示的补充说明。', verbose_name='公开备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('claimant_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='core.member', verbose_name='申请人')),
            ],
            options={
                'verbose_name': '报销申请',
                'verbose_name_plural': '报销申请',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FinanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(default=core.models.finance._new_review_id, max_length=64, unique=True, verbose_name='审核 ID')),
                ('decision', models.CharField(choices=[('approved', '已批准'), ('rejected', '已拒绝')], max_length=16, verbose_name='审核决定')),
                ('reason', models.TextField(blank=True, help_text='拒绝时必须填写理由。', verbose_name='审核理由')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.expenseclaim', verbose_name='报销申请')),
                ('reviewer_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_reviews', to='core.member', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '财务审核',
                'verbose_name_plural': '财务审核',
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=core.models.finance._new_transaction_id, max_length=64, unique=True, verbose_name='流水 ID')),
                ('transaction_type', models.CharField(choices=[('reimbursement', '报销支出'), ('income', '收入'), ('expense', '支出'), ('correction', '冲正')], max_length=32, verbose_name='流水类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='货币')),
                ('direction', models.CharField(choices=[('in', '入账'), ('out', '出账')], help_text='入账 or 出账。', max_length=8, verbose_name='方向')),
                ('summary', models.CharField(max_length=255, verbose_name='摘要')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.expenseclaim', verbose_name='关联报销')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_transactions', to='core.member', verbose_name='记录人')),
            ],
            options={
                'verbose_name': '财务流水',
                'verbose_name_plural': '财务流水',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
    ]
