# Generated by Django 5.2.16 on 2026-07-22 10:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_systemevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='采纳时间'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_offers', to='core.member', verbose_name='采纳人'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='decision_reason',
            field=models.TextField(blank=True, verbose_name='决策理由'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='decision_status',
            field=models.CharField(choices=[('submitted', '已提交'), ('under_review', '审核中'), ('accepted', '已采纳'), ('rejected', '已拒绝'), ('withdrawn', '已撤回'), ('fulfilled', '已履约'), ('cancelled', '已取消')], default='submitted', max_length=16, verbose_name='决策状态'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交付时间'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='offer_type',
            field=models.CharField(choices=[('quote', '报价'), ('donation', '捐赠')], default='quote', max_length=16, verbose_name='供给类型'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款时间'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='payment_status',
            field=models.CharField(choices=[('not_required', '无需付款'), ('pending', '待付款'), ('paid', '已付款'), ('disputed', '付款争议')], default='pending', max_length=16, verbose_name='付款状态'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='performance_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='core.credentialgrant', verbose_name='履约凭证'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='receipt_notes',
            field=models.TextField(blank=True, verbose_name='验收备注'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='receipt_status',
            field=models.CharField(choices=[('pending', '待验收'), ('accepted', '验收通过'), ('rejected', '验收未通过'), ('partial', '部分验收')], default='pending', max_length=16, verbose_name='验收状态'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_offers', to='core.member', verbose_name='验收人'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_offers', to='core.member', verbose_name='拒绝人'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='登录成员主体，提出报价/捐赠。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_offers', to='core.member', verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='partner_application',
            field=models.ForeignKey(blank=True, help_text='报价来源。可为空（直接由成员提交）。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='core.partnerapplication', verbose_name='合作方报名'),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='单价'),
        ),
    ]
