# Generated by Django 5.2.16 on 2026-07-22 12:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_supplierquote_accepted_at_supplierquote_accepted_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credentialgrant',
            name='unique_template_serial_no',
        ),
        migrations.RemoveConstraint(
            model_name='credentialgrant',
            name='unique_template_display_no',
        ),
        migrations.AddField(
            model_name='credentialgrant',
            name='dedupe_key',
            field=models.CharField(default='', help_text='业务去重键。同一 template+member 下唯一。', max_length=191, verbose_name='去重键'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='approval_tier',
            field=models.CharField(choices=[('small', '小额'), ('standard', '标准'), ('major', '大额')], default='small', max_length=16, verbose_name='审批层级'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='estimated_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='预估总金额'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='财务确认时间'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_approved_offers', to='core.member', verbose_name='财务确认人'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='governance_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='治理确认时间'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='governance_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_confirmed_offers', to='core.member', verbose_name='治理二次确认人'),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('credential_granted', '凭证已发放'), ('expense_claim_submitted', '报销申请已提交'), ('expense_claim_reviewed', '报销申请已审核'), ('expense_claim_paid', '报销已付款'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('supplier_offer_submitted', '供给报价已提交'), ('supplier_offer_accepted', '供给报价已采纳'), ('supplier_offer_rejected', '供给报价已拒绝'), ('supplier_offer_receipt_accepted', '供给报价验收通过'), ('supplier_offer_receipt_rejected', '供给报价验收失败'), ('supplier_offer_completed', '供给报价已完成'), ('supplier_offer_finance_approved', '供给报价财务已确认'), ('supplier_offer_governance_confirmed', '供给报价治理二次确认'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.AddConstraint(
            model_name='credentialgrant',
            constraint=models.UniqueConstraint(fields=('template', 'member', 'dedupe_key'), name='unique_template_member_dedupe_key'),
        ),
    ]
