# Generated by Django 5.2.16 on 2026-07-22 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_credentialgrant_unique_template_serial_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierquote',
            name='finance_approved_at',
        ),
        migrations.RemoveField(
            model_name='supplierquote',
            name='finance_approved_by',
        ),
        migrations.RemoveField(
            model_name='supplierquote',
            name='governance_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='supplierquote',
            name='governance_confirmed_by',
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('credential_granted', '凭证已发放'), ('expense_claim_submitted', '报销申请已提交'), ('expense_claim_reviewed', '报销申请已审核'), ('expense_claim_paid', '报销已付款'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('supplier_offer_submitted', '供给报价已提交'), ('supplier_offer_accepted', '供给报价已采纳'), ('supplier_offer_rejected', '供给报价已拒绝'), ('supplier_offer_receipt_accepted', '供给报价验收通过'), ('supplier_offer_receipt_rejected', '供给报价验收失败'), ('supplier_offer_completed', '供给报价已完成'), ('approval_proposal_submitted', '审批提案已提交'), ('approval_proposal_approved', '审批提案已通过'), ('approval_proposal_rejected', '审批提案已拒绝'), ('approval_proposal_executed', '审批提案已执行'), ('approval_proposal_cancelled', '审批提案已取消'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='ApprovalProposal',
            fields=[
                ('proposal_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='提案ID')),
                ('proposal_type', models.CharField(choices=[('procurement_acceptance', '采购采纳'), ('procurement_payment', '采购付款'), ('member_application', '成员申请'), ('inventory_adjustment', '库存调整'), ('dispute_resolution', '争议处理')], max_length=32, verbose_name='提案类型')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('public_reason', models.TextField(blank=True, verbose_name='公开理由')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('executed', '已执行')], default='submitted', max_length=16, verbose_name='状态')),
                ('approval_tier', models.CharField(choices=[('single', '单人'), ('standard', '标准'), ('major', '大额')], default='single', max_length=16, verbose_name='审批层级')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=128, verbose_name='目标ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='决议时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approval_proposals', to='core.member', verbose_name='提交人')),
            ],
            options={
                'verbose_name': '审批提案',
                'verbose_name_plural': '审批提案',
                'db_table': 'core_approval_proposal',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('approval_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='审批ID')),
                ('role', models.CharField(max_length=32, verbose_name='审批角色')),
                ('decision', models.CharField(choices=[('approved', '同意'), ('rejected', '拒绝')], max_length=16, verbose_name='决策')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审批时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to='core.member', verbose_name='审批人')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.approvalproposal', verbose_name='提案')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'db_table': 'core_approval_decision',
            },
        ),
        migrations.AddIndex(
            model_name='approvalproposal',
            index=models.Index(fields=['status'], name='core_approv_status_816519_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalproposal',
            index=models.Index(fields=['target_type', 'target_id'], name='core_approv_target__97bd4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(fields=('proposal', 'approver', 'role'), name='unique_approval_proposer_role'),
        ),
    ]
