# Generated by Django 5.2.16 on 2026-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_supplierquote_finance_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='accepts_offers',
            field=models.BooleanField(default=True, verbose_name='接受公开报价'),
        ),
    ]
