# Generated by Django 5.2.16 on 2026-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_resource_accepts_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalproposal',
            name='dedupe_key',
            field=models.CharField(default='', help_text='业务幂等键。同 proposal_type 下唯一。', max_length=191, verbose_name='去重键'),
        ),
        migrations.AddConstraint(
            model_name='approvalproposal',
            constraint=models.UniqueConstraint(fields=('proposal_type', 'dedupe_key'), name='unique_approval_proposal_type_dedupe_key'),
        ),
    ]
