# Generated by Django 5.2.16 on 2026-07-23 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_approvalproposal_dedupe_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='public_display_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='公开署名'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='public_visibility',
            field=models.CharField(choices=[('public', '公开'), ('anonymous', '匿名')], default='public', max_length=16, verbose_name='公开范围'),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('credential_granted', '凭证已发放'), ('expense_claim_submitted', '报销申请已提交'), ('expense_claim_reviewed', '报销申请已审核'), ('expense_claim_paid', '报销已付款'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('supplier_offer_submitted', '供给报价已提交'), ('supplier_offer_accepted', '供给报价已采纳'), ('supplier_offer_rejected', '供给报价已拒绝'), ('supplier_offer_receipt_accepted', '供给报价验收通过'), ('supplier_offer_receipt_rejected', '供给报价验收失败'), ('supplier_offer_completed', '供给报价已完成'), ('approval_proposal_submitted', '审批提案已提交'), ('approval_proposal_approved', '审批提案已通过'), ('approval_proposal_rejected', '审批提案已拒绝'), ('approval_proposal_executed', '审批提案已执行'), ('approval_proposal_cancelled', '审批提案已取消'), ('procurement_challenge_submitted', '采购质疑已提交'), ('procurement_challenge_reviewed', '采购质疑已处理'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='ProcurementChallenge',
            fields=[
                ('challenge_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='质疑ID')),
                ('challenge_type', models.CharField(choices=[('question', '质疑/提问'), ('lower_price', '更低价'), ('quality_concern', '质量疑虑'), ('alternative_supply', '替代供应')], max_length=32, verbose_name='质疑类型')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('accepted', '已采纳'), ('rejected', '已拒绝'), ('resolved', '已解决')], default='submitted', max_length=16, verbose_name='状态')),
                ('public_reason', models.TextField(verbose_name='公开理由')),
                ('proposed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='建议单价')),
                ('proposed_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='建议数量')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('review_reason', models.TextField(blank=True, verbose_name='处理理由')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('linked_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_sources', to='core.supplierquote', verbose_name='已转为正式报价')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='core.supplierquote', verbose_name='被质疑报价')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_challenges', to='core.member', verbose_name='处理人')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_challenges', to='core.member', verbose_name='提交人')),
            ],
            options={
                'verbose_name': '采购质疑',
                'verbose_name_plural': '采购质疑',
                'db_table': 'core_procurement_challenge',
                'ordering': ['-created_at'],
            },
        ),
    ]
