# Generated by Django 5.2.16 on 2026-07-23 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_supplierquote_public_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('rule_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='规则ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('domain', models.CharField(choices=[('resource', '资源库存'), ('capacity', '承载力'), ('dispute', '争议'), ('simulation', '模拟'), ('procurement', '采购'), ('provider', '供应者'), ('system', '系统')], max_length=16, verbose_name='领域')),
                ('metric_key', models.CharField(blank=True, max_length=64, verbose_name='指标键')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=16, verbose_name='严重程度')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('private', '私密')], default='public', max_length=16, verbose_name='可见性')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16, verbose_name='状态')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='阈值')),
                ('threshold_operator', models.CharField(default='lte', max_length=8, verbose_name='阈值运算符')),
                ('window_minutes', models.PositiveIntegerField(default=0, verbose_name='窗口分钟')),
                ('responsible_role', models.CharField(blank=True, max_length=32, verbose_name='责任角色')),
                ('auto_create_public_event', models.BooleanField(default=True, verbose_name='自动创建公开事件')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新')),
            ],
            options={
                'verbose_name': '风险规则',
                'verbose_name_plural': '风险规则',
                'db_table': 'core_risk_rule',
            },
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('credential_granted', '凭证已发放'), ('expense_claim_submitted', '报销申请已提交'), ('expense_claim_reviewed', '报销申请已审核'), ('expense_claim_paid', '报销已付款'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('dispute_created', '申诉已提交'), ('dispute_review_started', '申诉已受理'), ('dispute_resolved', '申诉已处理'), ('resource_adjusted', '资源已调整'), ('supplier_offer_submitted', '供给报价已提交'), ('supplier_offer_accepted', '供给报价已采纳'), ('supplier_offer_rejected', '供给报价已拒绝'), ('supplier_offer_receipt_accepted', '供给报价验收通过'), ('supplier_offer_receipt_rejected', '供给报价验收失败'), ('supplier_offer_completed', '供给报价已完成'), ('approval_proposal_submitted', '审批提案已提交'), ('approval_proposal_approved', '审批提案已通过'), ('approval_proposal_rejected', '审批提案已拒绝'), ('approval_proposal_executed', '审批提案已执行'), ('approval_proposal_cancelled', '审批提案已取消'), ('procurement_challenge_submitted', '采购质疑已提交'), ('procurement_challenge_reviewed', '采购质疑已处理'), ('risk_alert_triggered', '风险告警已触发'), ('risk_alert_acknowledged', '风险告警已确认'), ('risk_alert_resolved', '风险告警已解除'), ('risk_alert_dismissed', '风险告警已忽略'), ('risk_rule_updated', '风险规则已更新'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('alert_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='告警ID')),
                ('domain', models.CharField(choices=[('resource', '资源库存'), ('capacity', '承载力'), ('dispute', '争议'), ('simulation', '模拟'), ('procurement', '采购'), ('provider', '供应者'), ('system', '系统')], max_length=16, verbose_name='领域')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=16, verbose_name='严重程度')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('private', '私密')], default='public', max_length=16, verbose_name='可见性')),
                ('status', models.CharField(choices=[('active', '活跃'), ('acknowledged', '已确认'), ('investigating', '调查中'), ('resolved', '已解除'), ('dismissed', '已忽略')], default='active', max_length=16, verbose_name='状态')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('dedupe_key', models.CharField(help_text='唯一键：domain:source_type:source_id:metric_key', max_length=191, unique=True, verbose_name='去重键')),
                ('source_type', models.CharField(max_length=64, verbose_name='来源类型')),
                ('source_id', models.CharField(max_length=128, verbose_name='来源ID')),
                ('source_url', models.CharField(blank=True, max_length=256, verbose_name='来源链接')),
                ('metric_key', models.CharField(blank=True, max_length=64, verbose_name='指标键')),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='指标值')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='阈值')),
                ('responsible_role', models.CharField(blank=True, max_length=32, verbose_name='责任角色')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次发现')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后发现')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理记录')),
                ('public_note', models.TextField(blank=True, verbose_name='公开说明')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_risks', to='core.member')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_risks', to='core.member')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='core.riskrule')),
            ],
            options={
                'verbose_name': '风险告警',
                'verbose_name_plural': '风险告警',
                'db_table': 'core_risk_alert',
                'indexes': [models.Index(fields=['status'], name='core_risk_a_status_3b0310_idx'), models.Index(fields=['severity'], name='core_risk_a_severit_520beb_idx'), models.Index(fields=['domain'], name='core_risk_a_domain_1da18c_idx'), models.Index(fields=['source_type', 'source_id'], name='core_risk_a_source__fdd10e_idx')],
            },
        ),
    ]
