# Generated by Django 5.2.16 on 2026-07-24 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_riskrule_alter_systemevent_event_type_riskalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('account_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='账户ID')),
                ('account_type', models.CharField(choices=[('issuance_pool', '发行池'), ('task_locked', '任务锁定'), ('member', '成员'), ('frozen', '冻结'), ('burn', '销毁')], max_length=24, verbose_name='账户类型')),
                ('status', models.CharField(choices=[('active', '正常'), ('frozen', '已冻结'), ('closed', '已关闭')], default='active', max_length=16, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('member', models.OneToOneField(blank=True, help_text='成员账户与 Member 一一对应；系统账户此项为空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_account', to='core.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '积分账户',
                'verbose_name_plural': '积分账户',
                'db_table': 'core_credit_account',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='交易ID')),
                ('transaction_type', models.CharField(choices=[('issuance', '发行'), ('lock', '预算锁定'), ('unlock', '预算退回'), ('task_reward', '任务奖励'), ('transfer', '自由转账'), ('consume', '消费冻结'), ('burn', '销毁'), ('freeze', '冻结'), ('unfreeze', '解冻'), ('correction', '更正'), ('reversal', '冲正')], max_length=24, verbose_name='交易类型')),
                ('amount', models.IntegerField(help_text='正数，实际转移的积分数量。', verbose_name='积分数量')),
                ('related_event_id', models.CharField(blank=True, max_length=64, verbose_name='关联事件ID')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('idempotency_key', models.CharField(blank=True, default='', help_text='服务层幂等去重键；非空时同键重复 POST 不重复记账。', max_length=191, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('posted', '已入账'), ('void', '已作废')], default='posted', max_length=16, verbose_name='状态')),
                ('prev_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='前一交易哈希')),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='交易哈希')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_credit_txns', to='core.member', verbose_name='发起人')),
                ('related_ledger_entry', models.ForeignKey(blank=True, help_text='成员视角 LedgerEntry 投影。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='core.ledgerentry', verbose_name='关联流水投影')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='core.task', verbose_name='关联任务')),
                ('reverses_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='core.credittransaction', verbose_name='冲正原交易')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_credit_txns', to='core.member', verbose_name='审核人')),
                ('source_account', models.ForeignKey(blank=True, help_text='积分从此账户转出。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='core.creditaccount', verbose_name='来源账户')),
                ('target_account', models.ForeignKey(blank=True, help_text='积分转入此账户。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='core.creditaccount', verbose_name='目标账户')),
            ],
            options={
                'verbose_name': '积分交易',
                'verbose_name_plural': '积分交易',
                'db_table': 'core_credit_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['account_type'], name='core_credit_account_1a60bd_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['member'], name='core_credit_member__1c2c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['source_account'], name='core_credit_source__a50027_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['target_account'], name='core_credit_target__9dae70_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='core_credit_transac_02d313_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['status'], name='core_credit_status_115bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['related_task'], name='core_credit_related_9bee48_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['created_at'], name='core_credit_created_129815_idx'),
        ),
    ]
