# Generated by Django 5.2.16 on 2026-07-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_creditaccount_credittransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, help_text='数据库级唯一（plain unique，无 conditional）。NULL 允许多笔；非空重复即冲突。', max_length=191, null=True, unique=True, verbose_name='幂等键'),
        ),
    ]
