# Generated by Django 5.2.16 on 2026-07-24 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_credittransaction_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionOrder',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('status', models.CharField(choices=[('pending', '待履约'), ('fulfilled', '已履约'), ('cancelled', '已取消'), ('disputed', '争议中'), ('reversed', '已冲正')], default='pending', max_length=16, verbose_name='状态')),
                ('item_type', models.CharField(choices=[('meal', '餐食'), ('goods', '物资'), ('resource_use', '资源使用'), ('room_upgrade', '房间升级'), ('storage', '仓储'), ('parking', '泊车'), ('training', '培训'), ('service', '服务'), ('fee_reduction', '费用减免'), ('other', '其他')], default='other', max_length=24, verbose_name='项目类型')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('original_amount_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价(元)')),
                ('credit_amount', models.IntegerField(verbose_name='积分数量')),
                ('cash_amount_rmb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='现金(元)')),
                ('related_event_id', models.CharField(blank=True, max_length=64, verbose_name='关联事件ID')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='履约时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_redemption_orders', to='core.member', verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_orders', to='core.member', verbose_name='成员')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_orders', to='core.task', verbose_name='关联任务')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_redemption_orders', to='core.member', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '兑换订单',
                'verbose_name_plural': '兑换订单',
                'db_table': 'core_redemption_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='core_redemp_member__269354_idx'), models.Index(fields=['status'], name='core_redemp_status_69f0ef_idx')],
            },
        ),
    ]
