# Generated by Django 5.2.16 on 2026-07-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_redemptionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionorder',
            name='finance_treatment_ref',
            field=models.CharField(blank=True, help_text='后续财务处理的外部引用标识。', max_length=128, verbose_name='财务处理引用'),
        ),
        migrations.AddField(
            model_name='redemptionorder',
            name='item_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='兑换项目结构化快照。', verbose_name='商品/服务快照'),
        ),
        migrations.AddField(
            model_name='redemptionorder',
            name='resource_id',
            field=models.CharField(blank=True, help_text='关联 Resource.resource_id。', max_length=96, verbose_name='关联资源ID'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='业务发起人（不一定是系统操作员）。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_credit_txns', to='core.member', verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='扩展结构化数据。不在公开页展示。', verbose_name='扩展数据'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='related_event_id',
            field=models.CharField(blank=True, help_text='关联 SystemEvent.event_id，构成审计哈希链。', max_length=64, verbose_name='关联事件ID'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='治理/财务审核人。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_credit_txns', to='core.member', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='redemptionorder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='扩展结构化数据。不在公开页展示。', verbose_name='扩展数据'),
        ),
        migrations.AlterField(
            model_name='redemptionorder',
            name='related_event_id',
            field=models.CharField(blank=True, help_text='关联 SystemEvent.event_id，用于审计链。', max_length=64, verbose_name='关联事件ID'),
        ),
    ]
