# Generated by Django 5.2.16 on 2026-07-25 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_redemptionorder_finance_treatment_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('merchant_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='商户ID')),
                ('display_name', models.CharField(max_length=128, verbose_name='商户名称')),
                ('merchant_type', models.CharField(choices=[('member_micro_merchant', '成员微创业'), ('cash_settlement_merchant', '现金结算商户')], max_length=32, verbose_name='商户类型')),
                ('status', models.CharField(choices=[('active', '营业中'), ('suspended', '已暂停'), ('closed', '已关闭')], default='active', max_length=16, verbose_name='状态')),
                ('settlement_rate', models.DecimalField(blank=True, decimal_places=4, help_text='仅 cash_settlement 商户使用。如 0.5 表示 1 积分 = 0.5 元人民币。结算快照存入 settlement record，不受后续修改影响。', max_digits=8, null=True, verbose_name='结算汇率')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('operator_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_merchants', to='core.member', verbose_name='经营成员')),
            ],
            options={
                'verbose_name': '商户资料',
                'verbose_name_plural': '商户资料',
                'db_table': 'core_merchant_profile',
            },
        ),
        migrations.CreateModel(
            name='MerchantSettlementRecord',
            fields=[
                ('settlement_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='结算ID')),
                ('covered_credit_amount', models.IntegerField(verbose_name='覆盖积分数')),
                ('settlement_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='结算汇率')),
                ('payable_rmb', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='应付人民币')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('approved', '已批准'), ('paid', '已付款'), ('disputed', '争议'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('reason', models.TextField(blank=True, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_records', to='core.merchantprofile', verbose_name='商户')),
                ('redemption_order', models.OneToOneField(help_text='关联的兑换订单。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_record', to='core.redemptionorder', verbose_name='兑换订单')),
            ],
            options={
                'verbose_name': '商户结算记录',
                'verbose_name_plural': '商户结算记录',
                'db_table': 'core_merchant_settlement_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['merchant_type'], name='core_mercha_merchan_1e9ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['operator_member'], name='core_mercha_operato_fe1370_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantsettlementrecord',
            index=models.Index(fields=['merchant', 'status'], name='core_mercha_merchan_50737e_idx'),
        ),
    ]
