# Generated by Django 5.2.16 on 2026-07-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merchantprofile_merchantsettlementrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionorder',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='现金结算商户。空表示普通成员兑换。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_orders', to='core.merchantprofile', verbose_name='商户'),
        ),
    ]
