# Generated by Django 5.2.16 on 2026-07-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_redemptionorder_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_id',
            field=models.CharField(help_text='商户唯一标识。现金结算商户不持有积分账户。', max_length=64, primary_key=True, serialize=False, verbose_name='商户ID'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_type',
            field=models.CharField(choices=[('member_micro_merchant', '成员微创业'), ('cash_settlement_merchant', '现金结算商户')], help_text='cash_settlement_merchant 积分消费后销毁并生成人民币应付款；member_micro_merchant 使用自由转账，不生成结算。', max_length=32, verbose_name='商户类型'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='operator_member',
            field=models.ForeignKey(blank=True, help_text='经营该商户的成员。商户不拥有独立的积分账户。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_merchants', to='core.member', verbose_name='经营成员'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='settlement_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='仅 cash_settlement 商户使用。如 0.5 表示 1 积分 = 0.5 元人民币。履约时快照写入 settlement record，不受后续修改影响。', max_digits=8, null=True, verbose_name='结算汇率'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(choices=[('active', '营业中'), ('suspended', '已暂停'), ('closed', '已关闭')], default='active', help_text='营业状态。非 active 商户不能接受新兑换订单。', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='merchantsettlementrecord',
            name='covered_credit_amount',
            field=models.IntegerField(help_text='本次结算覆盖的消费积分数（不是商户积分余额）。商户不持有可流通积分。', verbose_name='覆盖积分数'),
        ),
        migrations.AlterField(
            model_name='merchantsettlementrecord',
            name='payable_rmb',
            field=models.DecimalField(decimal_places=2, help_text='人民币应付结算金额（不是积分提现）。按两位小数量化。', max_digits=12, verbose_name='应付人民币'),
        ),
        migrations.AlterField(
            model_name='merchantsettlementrecord',
            name='redemption_order',
            field=models.OneToOneField(help_text='关联的兑换订单。每笔结算必须对应一笔订单。', on_delete=django.db.models.deletion.PROTECT, related_name='settlement_record', to='core.redemptionorder', verbose_name='兑换订单'),
        ),
        migrations.AlterField(
            model_name='merchantsettlementrecord',
            name='settlement_rate',
            field=models.DecimalField(decimal_places=4, help_text='履约时快照写入的结算汇率，不受商户配置后续修改影响。', max_digits=8, verbose_name='结算汇率'),
        ),
        migrations.AlterField(
            model_name='merchantsettlementrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待结算'), ('approved', '已批准'), ('paid', '已付款'), ('disputed', '争议'), ('cancelled', '已取消')], default='pending', help_text='pending 表示已生成应付款记录但尚未批准/支付。', max_length=16, verbose_name='状态'),
        ),
    ]
