# Generated by Django 5.2.16 on 2026-07-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_merchantprofile_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='member',
            field=models.OneToOneField(blank=True, help_text='仅 member 类型账户使用；系统账户(issuance_pool/task_locked/frozen/burn)此项必须为 None。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_account', to='core.member', verbose_name='成员'),
        ),
    ]
