# Generated by Django 5.2.16 on 2026-08-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_standardize_roles_and_electorate_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proposal',
            new_name='core_propos_elector_1b905e_idx',
            old_name='core_propos_rule_status_idx',
        ),
        migrations.AlterField(
            model_name='capacityassessment',
            name='current_contributors',
            field=models.PositiveIntegerField(verbose_name='当前贡献者数'),
        ),
        migrations.AlterField(
            model_name='capacityassessment',
            name='current_covenanters',
            field=models.PositiveIntegerField(verbose_name='当前守约者数'),
        ),
        migrations.AlterField(
            model_name='communityfeedback',
            name='official_response',
            field=models.TextField(blank=True, help_text='典守者的公开回应。', verbose_name='官方回应'),
        ),
        migrations.AlterField(
            model_name='communityfeedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, help_text='最近回应该反馈的典守者。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_community_feedbacks', to='core.member', verbose_name='回应人'),
        ),
        migrations.AlterField(
            model_name='credentialgrant',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, help_text='递增序列号，同一模板内唯一（如守约者编号 1,2,3…）。', null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='credentialtemplate',
            name='code',
            field=models.CharField(help_text='程序内唯一编码，例如 covenanter_number。', max_length=64, unique=True, verbose_name='凭证编码'),
        ),
        migrations.AlterField(
            model_name='credentialtemplate',
            name='credential_type',
            field=models.CharField(choices=[('covenanter_number', '守约者编号'), ('badge', '勋章'), ('certificate', '证书'), ('nft_placeholder', 'NFT占位')], max_length=32, verbose_name='凭证类型'),
        ),
        migrations.AlterField(
            model_name='credentialtemplate',
            name='template_id',
            field=models.CharField(help_text='稳定的业务 ID，例如 credential-template-covenanter-number。', max_length=128, unique=True, verbose_name='模板 ID'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='执行准入提案或拒绝的典守者；不再表示单人审核。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_member_applications', to='core.member', verbose_name='决议人'),
        ),
    ]
