# Generated by Django 5.2.16 on 2026-08-03 13:49

import core.models.attachments
import core.models.finance
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_member_profile_managed_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(default=core.models.attachments._new_attachment_id, max_length=64, unique=True, verbose_name='附件 ID')),
                ('object_key', models.CharField(help_text='私有存储中的不可预测对象标识。', max_length=512, unique=True, verbose_name='对象 key')),
                ('detected_media_type', models.CharField(help_text='由服务端内容识别得到的媒体类型。', max_length=128, verbose_name='检测媒体类型')),
                ('display_filename', models.CharField(help_text='去除路径后的用户可见文件名，仅用于私有下载提示。', max_length=255, verbose_name='显示文件名')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='字节数')),
                ('sha256', models.CharField(help_text='原始保留字节的十六进制摘要。', max_length=64, verbose_name='SHA-256')),
                ('audience', models.CharField(choices=[('private', '私有'), ('public', '公开')], default='private', max_length=16, verbose_name='受众')),
                ('lifecycle', models.CharField(choices=[('sealed', '已密封'), ('superseded', '已更正'), ('withdrawn', '已撤回')], default='sealed', max_length=16, verbose_name='生命周期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source_attachment', models.ForeignKey(blank=True, help_text='公开脱敏副本必须指向其私有来源原件。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_derivatives', to='core.attachment', verbose_name='来源原件')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_versions', to='core.attachment', verbose_name='更正前版本')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='core.member', verbose_name='上传人')),
            ],
            options={
                'verbose_name': '业务附件',
                'verbose_name_plural': '业务附件',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(default=core.models.finance._new_payment_execution_id, max_length=64, unique=True, verbose_name='付款执行 ID')),
                ('backend_type', models.CharField(help_text='产生付款结果的已注册能力后端标识。', max_length=64, verbose_name='执行后端')),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('failed', '失败')], max_length=16, verbose_name='执行状态')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('payment_method', models.CharField(max_length=64, verbose_name='付款方式')),
                ('note', models.TextField(blank=True, verbose_name='内部备注')),
                ('external_system', models.CharField(blank=True, max_length=64, verbose_name='外部系统')),
                ('external_object_id', models.CharField(blank=True, max_length=255, verbose_name='外部对象 ID')),
                ('sync_status', models.CharField(choices=[('local', '本地'), ('synced', '已同步'), ('failed', '同步失败')], default='local', max_length=16, verbose_name='同步状态')),
                ('result_snapshot', models.JSONField(blank=True, default=dict, help_text='经过字段白名单过滤的后端结果副本。', verbose_name='结果快照')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_execution', to='core.expenseclaim', verbose_name='报销申请')),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_execution', to='core.financetransaction', verbose_name='财务流水')),
                ('payer_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_executions', to='core.member', verbose_name='付款确认人')),
            ],
            options={
                'verbose_name': '付款执行',
                'verbose_name_plural': '付款执行',
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('expense_evidence', '支出凭证'), ('payment_evidence', '付款凭证'), ('public_material', '公开材料')], max_length=32, verbose_name='用途')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_link', to='core.attachment', verbose_name='附件')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='core.expenseclaim', verbose_name='报销申请')),
                ('payment_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='core.paymentexecution', verbose_name='付款执行')),
            ],
            options={
                'verbose_name': '报销附件关联',
                'verbose_name_plural': '报销附件关联',
            },
        ),
    ]
