# Generated by Django 5.2.16 on 2026-08-03 16:41

import core.models.deliberator_exams
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_deliberator_exam(apps, schema_editor):
    Policy = apps.get_model('core', 'DeliberatorExamPolicy')
    Question = apps.get_model('core', 'DeliberatorExamQuestion')
    database_alias = schema_editor.connection.alias
    Question.objects.using(database_alias).get_or_create(
        question_id='delib-question-governance-baseline', version=1,
        defaults={
            'prompt': '谁可以参与守约者准入申请的表决？',
            'options_json': [
                {'id': 'a', 'text': '同时具有有效守约者资格和执衡者任期的成员'},
                {'id': 'b', 'text': '任何已注册账号'},
                {'id': 'c', 'text': '只有 Django 超级管理员'},
            ],
            'correct_option_id': 'a', 'points': 1,
            'explanation': '成员准入选民必须同时满足守约者资格和执衡者任期。',
            'status': 'published', 'published_at': timezone.now(),
        },
    )
    Policy.objects.using(database_alias).get_or_create(
        version=1,
        defaults={
            'policy_id': 'delib-policy-baseline-v1', 'question_count': 1,
            'passing_percent': 100, 'status': 'active', 'published_at': timezone.now(),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_attachment_paymentexecution_expenseclaimattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliberatorExamPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(default=core.models.deliberator_exams._new_policy_id, max_length=64, unique=True, verbose_name='政策 ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='版本')),
                ('question_count', models.PositiveSmallIntegerField(default=1, verbose_name='抽题数量')),
                ('passing_percent', models.PositiveSmallIntegerField(default=100, verbose_name='及格百分比')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('retired', '已停用')], default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_deliberator_exam_policies', to='core.member', verbose_name='发布人')),
            ],
            options={
                'verbose_name': '执衡者考试政策',
                'verbose_name_plural': '执衡者考试政策',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='DeliberatorExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.CharField(default=core.models.deliberator_exams._new_attempt_id, max_length=64, unique=True, verbose_name='考试尝试 ID')),
                ('policy_version', models.PositiveIntegerField(help_text='开始考试时生效的政策版本快照。', verbose_name='政策版本')),
                ('question_snapshot_json', models.JSONField(default=list, help_text='私有不可变快照，包含评分所需正确答案，不得公开。', verbose_name='题目与评分快照')),
                ('answers_json', models.JSONField(blank=True, default=dict, verbose_name='作答')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='得分')),
                ('total_points', models.PositiveIntegerField(verbose_name='总分')),
                ('passing_score', models.PositiveIntegerField(verbose_name='及格分')),
                ('status', models.CharField(choices=[('in_progress', '答题中'), ('passed', '已通过'), ('failed', '未通过'), ('invalidated', '资格失效')], default='in_progress', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliberator_exam_attempts', to='core.member', verbose_name='成员')),
                ('role_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliberator_exam_attempt', to='core.roleassignment', verbose_name='产生的执衡者任期')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.deliberatorexampolicy', verbose_name='考试政策')),
            ],
            options={
                'verbose_name': '执衡者考试尝试',
                'verbose_name_plural': '执衡者考试尝试',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['member', 'status'], name='core_delibe_member__6dbf85_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliberatorExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default=core.models.deliberator_exams._new_question_id, help_text='同一道题不同版本共用的稳定标识。', max_length=64, verbose_name='题目 ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('prompt', models.TextField(verbose_name='题干')),
                ('options_json', models.JSONField(default=list, help_text='选项列表，每项包含稳定 id 和显示文本。', verbose_name='选项')),
                ('correct_option_id', models.CharField(help_text='仅用于服务端评分，不得输出到普通成员页面或日志。', max_length=64, verbose_name='正确选项 ID')),
                ('explanation', models.TextField(blank=True, help_text='仅供题库维护和内部审计，不向考生显示。', verbose_name='解释')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='分值')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已停用')], default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_deliberator_exam_questions', to='core.member', verbose_name='创建人')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_deliberator_exam_questions', to='core.member', verbose_name='发布人')),
            ],
            options={
                'verbose_name': '执衡者考试题目',
                'verbose_name_plural': '执衡者考试题目',
                'ordering': ('question_id', '-version'),
                'constraints': [models.UniqueConstraint(fields=('question_id', 'version'), name='unique_deliberator_question_version')],
            },
        ),
        migrations.RunPython(seed_deliberator_exam, migrations.RunPython.noop),
    ]
