# Generated by Django 5.2.16 on 2026-08-08 06:14

from django.db import migrations, models


def populate_active_policy_slot(apps, schema_editor):
    Policy = apps.get_model("core", "DeliberatorExamPolicy")
    database_alias = schema_editor.connection.alias
    active = list(
        Policy.objects.using(database_alias)
        .filter(status="active")
        .order_by("-version", "-pk")
    )
    if not active:
        return
    Policy.objects.using(database_alias).filter(
        pk__in=[policy.pk for policy in active[1:]],
    ).update(status="retired", active_slot=None)
    Policy.objects.using(database_alias).filter(pk=active[0].pk).update(active_slot=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_systemevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberatorexampolicy',
            name='active_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='仅生效政策写入固定值 1，利用数据库唯一约束保证每个 world 至多一项生效政策。', null=True, unique=True, verbose_name='生效唯一槽位'),
        ),
        migrations.RunPython(populate_active_policy_slot, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='deliberatorexampolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_slot', 1), ('status', 'active')), models.Q(models.Q(('status', 'active'), _negated=True), ('active_slot__isnull', True)), _connector='OR'), name='deliberator_policy_active_slot_consistent'),
        ),
    ]
