# Generated by Django 5.2.16 on 2026-08-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rename_administrator_role_semantics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfeedback',
            name='official_response',
            field=models.TextField(blank=True, help_text='管理员的公开回应。', verbose_name='官方回应'),
        ),
        migrations.AlterField(
            model_name='communityfeedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, help_text='最近回应该反馈的管理员。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_community_feedbacks', to='core.member', verbose_name='回应人'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='执行准入提案或拒绝的管理员；不再表示单人审核。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_member_applications', to='core.member', verbose_name='决议人'),
        ),
    ]
