# Generated by Django 5.2.16 on 2026-08-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_communityfeedback_official_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='related_dispute_id',
        ),
        migrations.AddField(
            model_name='event',
            name='related_feedback_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='关联反馈ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('system', '系统'), ('simulation_day', '模拟日期'), ('task', '任务'), ('ledger', '账本'), ('resource', '资源'), ('event_feedback', '事件反馈'), ('capacity', '容量'), ('governance', '治理'), ('random_incident', '随机事件')], max_length=32, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('member_created', '成员已创建'), ('member_application_submitted', '成员报名已提交'), ('member_application_reviewed', '成员报名已审核'), ('partner_application_submitted', '合作方报名已提交'), ('partner_application_reviewed', '合作方报名已审核'), ('role_created', '角色已创建'), ('role_assigned', '任命'), ('role_revoked', '卸任'), ('deliberator_exam_question_changed', '执衡者题库已变更'), ('deliberator_exam_policy_changed', '执衡者考试政策已变更'), ('proposal_created', '提案已创建'), ('proposal_vote_cast', '提案已投票'), ('proposal_vote_changed', '提案已改票'), ('proposal_passed', '提案已通过'), ('proposal_failed', '提案未通过'), ('proposal_cancelled', '提案已取消'), ('proposal_executed', '提案已执行'), ('credential_granted', '凭证已发放'), ('expense_claim_submitted', '报销申请已提交'), ('expense_claim_reviewed', '报销申请已审核'), ('expense_claim_paid', '报销已付款'), ('task_created', '任务已创建'), ('task_published', '任务已发布'), ('task_assigned', '任务已指派'), ('task_claimed', '任务已领取'), ('task_submitted', '任务已提交'), ('task_reviewed', '任务已验收'), ('task_closed', '任务已关闭'), ('event_feedback_submitted', '事件反馈已提交'), ('event_feedback_verification_started', '事件反馈已开始核实'), ('event_feedback_response_requested', '事件反馈已请求回应'), ('event_feedback_responded', '事件反馈已回应'), ('event_feedback_concluded', '事件反馈已形成结论'), ('event_feedback_closed', '事件反馈已结束'), ('event_feedback_withdrawn', '事件反馈已撤回'), ('resource_adjusted', '资源已调整'), ('supplier_offer_submitted', '供给报价已提交'), ('supplier_offer_accepted', '供给报价已采纳'), ('supplier_offer_rejected', '供给报价已拒绝'), ('supplier_offer_receipt_accepted', '供给报价验收通过'), ('supplier_offer_receipt_rejected', '供给报价验收失败'), ('supplier_offer_completed', '供给报价已完成'), ('approval_proposal_submitted', '审批提案已提交'), ('approval_proposal_approved', '审批提案已通过'), ('approval_proposal_rejected', '审批提案已拒绝'), ('approval_proposal_executed', '审批提案已执行'), ('approval_proposal_cancelled', '审批提案已取消'), ('procurement_challenge_submitted', '采购质疑已提交'), ('procurement_challenge_reviewed', '采购质疑已处理'), ('risk_alert_triggered', '风险告警已触发'), ('risk_alert_acknowledged', '风险告警已确认'), ('risk_alert_resolved', '风险告警已解除'), ('risk_alert_dismissed', '风险告警已忽略'), ('risk_rule_updated', '风险规则已更新'), ('credit_earned', '积分获得'), ('credit_deducted', '积分扣减'), ('credit_adjusted', '积分调整'), ('credit_reversed', '积分冲正'), ('system_initialized', '系统初始化')], max_length=64, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('feedback_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='反馈ID')),
                ('feedback_type', models.CharField(choices=[('correction', '纠错'), ('opinion', '意见'), ('complaint', '投诉'), ('report', '举报'), ('review', '复核'), ('risk', '风险')], max_length=24, verbose_name='反馈类型')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('verifying', '核实中'), ('awaiting_response', '等待回应'), ('concluded', '已形成结论'), ('closed', '已结束'), ('withdrawn', '已撤回')], default='submitted', max_length=24, verbose_name='状态')),
                ('statement', models.TextField(verbose_name='事实陈述')),
                ('requested_outcome', models.TextField(blank=True, verbose_name='期望结果')),
                ('evidence_refs', models.JSONField(blank=True, default=list, help_text='仅保存稳定证据标识；公开输出不得直接暴露受保护凭据。', verbose_name='证据引用')),
                ('submitter_visibility', models.CharField(choices=[('public', '公开'), ('parties_and_handlers', '仅相关方和处理人'), ('handlers_only', '仅处理人')], default='public', help_text='只控制提交人身份展示，不改变系统内部实名记录。', max_length=24, verbose_name='提交人身份展示范围')),
                ('privacy_reason', models.TextField(blank=True, help_text='选择非公开身份展示范围时必填，仅处理者可见。', verbose_name='限制身份展示理由')),
                ('response_statement', models.TextField(blank=True, verbose_name='相关方回应')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回应时间')),
                ('conclusion', models.CharField(blank=True, choices=[('confirmed', '属实'), ('partly_confirmed', '部分属实'), ('not_confirmed', '不属实'), ('inconclusive', '无法核实'), ('not_applicable', '不适用')], max_length=24, verbose_name='结论')),
                ('conclusion_reason', models.TextField(blank=True, verbose_name='结论依据')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('verification_started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始核实时间')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='形成结论时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('assigned_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_event_feedbacks', to='core.member', verbose_name='核实责任人')),
                ('concluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concluded_event_feedbacks', to='core.member', verbose_name='结论责任人')),
                ('related_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='core.event', verbose_name='关联事件')),
                ('resolution_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_feedbacks', to='core.event', verbose_name='结果事件')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_event_feedbacks', to='core.member', verbose_name='回应人')),
                ('subject_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_event_feedbacks', to='core.member', verbose_name='相关方')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_event_feedbacks', to='core.member', verbose_name='提交人')),
            ],
            options={
                'verbose_name': '事件反馈',
                'verbose_name_plural': '事件反馈',
                'db_table': 'core_event_feedback',
                'ordering': ['-submitted_at', 'feedback_id'],
            },
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['status'], name='core_event__status_975288_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['submitted_by'], name='core_event__submitt_e08ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['assigned_handler'], name='core_event__assigne_9c6a62_idx'),
        ),
    ]
