# Generated by Django 5.2.14 on 2026-06-29 07:24

import django.utils.timezone
from django.db import migrations, models


def create_default_realworld(apps, schema_editor):
    WorldRegistry = apps.get_model("worlds", "WorldRegistry")
    WorldRegistry.objects.get_or_create(
        world_id="realworld",
        defaults={
            "name": "Real world",
            "world_type": "real",
            "database_alias": "realworld",
            "database_name": "dev_big_real",
            "status": "active",
        },
    )
    WorldRegistry.objects.get_or_create(
        world_id="simulation0001",
        defaults={
            "name": "Simulation 0001",
            "world_type": "simulation",
            "database_alias": "simulation0001",
            "database_name": "dev_big_sim0001",
            "status": "active",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldRegistry',
            fields=[
                ('world_id', models.CharField(help_text='Stable world id, for example realworld or simulation0001.', max_length=64, primary_key=True, serialize=False, verbose_name='world ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('world_type', models.CharField(choices=[('real', 'Real world'), ('simulation', 'Simulation world')], max_length=24, verbose_name='type')),
                ('database_alias', models.CharField(default='default', help_text='Alias in Django DATABASES, for example realworld or simulation0001.', max_length=64, verbose_name='database alias')),
                ('database_name', models.CharField(blank=True, max_length=128, verbose_name='database name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=24, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
            ],
            options={
                'verbose_name': 'world registry',
                'verbose_name_plural': 'world registry',
                'ordering': ['world_id'],
                'indexes': [models.Index(fields=['world_type', 'status'], name='worlds_worl_world_t_fd2a33_idx'), models.Index(fields=['database_alias'], name='worlds_worl_databas_fedcf3_idx')],
            },
        ),
        migrations.RunPython(create_default_realworld, migrations.RunPython.noop),
    ]
