# Generated by Django 5.2.14 on 2026-07-01 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldregistry',
            options={'ordering': ['world_id'], 'verbose_name': '世界注册表', 'verbose_name_plural': '世界注册表'},
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='database_alias',
            field=models.CharField(default='default', help_text='Django DATABASES 中配置的别名，例如 realworld 或 simulation0001。', max_length=64, verbose_name='数据库别名'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='database_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='name',
            field=models.CharField(max_length=120, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('archived', '已归档'), ('deleted', '已删除')], default='active', max_length=24, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='world_id',
            field=models.CharField(help_text='稳定世界 ID，例如 realworld 或 simulation0001。', max_length=64, primary_key=True, serialize=False, verbose_name='世界ID'),
        ),
        migrations.AlterField(
            model_name='worldregistry',
            name='world_type',
            field=models.CharField(choices=[('real', '真实世界'), ('simulation', '仿真世界')], max_length=24, verbose_name='世界类型'),
        ),
    ]
