# Generated by Django 5.2.16 on 2026-07-15 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_alter_worldregistry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reset_zero_start', '重置到零起点基线')], help_text='维护操作标识，例如 reset_zero_start。', max_length=64, verbose_name='操作类型')),
                ('actor_username', models.CharField(help_text='执行维护操作的 Django 用户名。', max_length=150, verbose_name='操作人')),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('failed', '失败')], help_text='操作最终状态：成功或失败。', max_length=32, verbose_name='执行状态')),
                ('force', models.BooleanField(default=False, help_text='是否绕过未处置运行的保护机制强制执行。', verbose_name='强制模式')),
                ('counts_before_json', models.JSONField(blank=True, default=dict, help_text='操作前目标世界各核心表的记录数量。', verbose_name='清空前记录数')),
                ('counts_after_json', models.JSONField(blank=True, default=dict, help_text='操作后（重新 seed 后）目标世界各核心表的记录数量。', verbose_name='清空后记录数')),
                ('message', models.TextField(blank=True, help_text='操作结果或失败原因的补充说明。', verbose_name='结果消息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('world', models.ForeignKey(help_text='被维护操作作用的目标世界注册表记录。', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='worlds.worldregistry', verbose_name='目标世界')),
            ],
            options={
                'verbose_name': '世界维护日志',
                'verbose_name_plural': '世界维护日志',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['world', 'action'], name='worlds_worl_world_i_f68aa0_idx'), models.Index(fields=['status'], name='worlds_worl_status_0babbe_idx')],
            },
        ),
    ]
