"""Static project-plan demo seed specs."""

from __future__ import annotations

from core.models import PlanCapacityImpact, PlanDependency, PlanNode
from simulation.responsibility_closure import photovoltaic_responsibility_closure_requirements


def plan_node_specs():
    plan_node_specs = [
        {
            "code": "R0",
            "title": "招募与组队",
            "node_type": PlanNode.NodeType.STAGE,
            "status": PlanNode.Status.COMPLETED,
            "duration": 14,
            "cost": 50000,
            "people": (3, 8),
            "person_days": 70,
            "criteria": ["完成开荒队角色定义", "形成可出发人员名单", "关键岗位不少于 12 类"],
        },
        {
            "code": "R1",
            "parent": "R0",
            "title": "发布招募简章和岗位清单",
            "node_type": PlanNode.NodeType.RECRUITMENT,
            "status": PlanNode.Status.COMPLETED,
            "duration": 3,
            "cost": 10000,
            "people": (2, 4),
            "person_days": 10,
            "skills": ["招募", "传播", "岗位设计"],
            "criteria": ["发布公开招募说明", "列出食堂、仓储、维修、治理等岗位"],
        },
        {
            "code": "R2",
            "parent": "R0",
            "title": "候选人筛选与能力盘点",
            "node_type": PlanNode.NodeType.RECRUITMENT,
            "status": PlanNode.Status.COMPLETED,
            "duration": 7,
            "cost": 25000,
            "people": (5, 10),
            "person_days": 45,
            "skills": ["面试", "技能评估", "风险识别"],
            "criteria": ["完成候选人画像", "识别关键技能缺口", "形成第一批出发名单"],
        },
        {
            "code": "R3",
            "parent": "R0",
            "title": "出发承诺与行前准备",
            "node_type": PlanNode.NodeType.RECRUITMENT,
            "status": PlanNode.Status.COMPLETED,
            "duration": 4,
            "cost": 15000,
            "people": (3, 6),
            "person_days": 24,
            "criteria": ["完成基础规则确认", "完成个人物资清单", "确认预计抵达时间"],
        },
        {
            "code": "A0",
            "title": "分批抵达与临时集结",
            "node_type": PlanNode.NodeType.STAGE,
            "status": PlanNode.Status.COMPLETED,
            "duration": 5,
            "cost": 120000,
            "people": (10, 30),
            "person_days": 120,
            "criteria": ["先遣队抵达", "登记所有成员实际抵达时间", "建立临时住宿和点名机制"],
        },
        {
            "code": "A1",
            "parent": "A0",
            "title": "先遣队抵达并建立临时指挥点",
            "node_type": PlanNode.NodeType.ARRIVAL,
            "status": PlanNode.Status.COMPLETED,
            "duration": 1,
            "cost": 30000,
            "people": (8, 15),
            "person_days": 15,
            "criteria": ["指挥点可通信", "完成首日安全检查", "形成先遣工作日志"],
        },
        {
            "code": "A2",
            "parent": "A0",
            "title": "分批抵达登记和临时安置",
            "node_type": PlanNode.NodeType.ARRIVAL,
            "status": PlanNode.Status.COMPLETED,
            "duration": 4,
            "cost": 60000,
            "people": (8, 20),
            "person_days": 80,
            "criteria": ["登记抵达成员", "标记迟到和失联风险", "每人有临时休息位置"],
        },
        {
            "code": "M0",
            "title": "现场评估与开荒会议",
            "node_type": PlanNode.NodeType.STAGE,
            "status": PlanNode.Status.COMPLETED,
            "duration": 3,
            "cost": 80000,
            "people": (20, 60),
            "person_days": 150,
            "criteria": ["完成环境评估", "完成资源清点", "发布第一版执行计划"],
        },
        {
            "code": "M1",
            "parent": "M0",
            "title": "目标地点环境勘查",
            "node_type": PlanNode.NodeType.WORK_PACKAGE,
            "status": PlanNode.Status.COMPLETED,
            "duration": 1,
            "cost": 30000,
            "people": (6, 12),
            "person_days": 12,
            "skills": ["测绘", "安全", "水电"],
            "criteria": ["完成水、电、交通、卫生和安全风险清单"],
        },
        {
            "code": "M2",
            "parent": "M0",
            "title": "资源、技能和设备清点",
            "node_type": PlanNode.NodeType.OPERATIONS,
            "status": PlanNode.Status.COMPLETED,
            "duration": 1,
            "cost": 10000,
            "people": (8, 16),
            "person_days": 16,
            "criteria": ["完成资源台账", "完成人员技能台账", "标出关键短缺项"],
        },
        {
            "code": "M3",
            "parent": "M0",
            "title": "召开执行计划会议并发布初版计划",
            "node_type": PlanNode.NodeType.GOVERNANCE,
            "status": PlanNode.Status.COMPLETED,
            "duration": 1,
            "cost": 40000,
            "people": (30, 100),
            "person_days": 80,
            "criteria": ["确定初步开荒完成标准", "确定 30 天目标", "确定负责人和复盘节奏"],
        },
        {
            "code": "B0",
            "title": "初步开荒基础设施",
            "node_type": PlanNode.NodeType.STAGE,
            "status": PlanNode.Status.IN_PROGRESS,
            "duration": 18,
            "cost": 1800000,
            "people": (40, 100),
            "person_days": 1200,
            "criteria": ["可稳定支持 100 人基本生活", "食宿水电仓储卫生达到安全线", "形成可复制任务制度"],
        },
        {
            "code": "B1",
            "parent": "B0",
            "title": "建立临时公共食堂",
            "node_type": PlanNode.NodeType.WORK_PACKAGE,
            "status": PlanNode.Status.IN_PROGRESS,
            "duration": 5,
            "cost": 220000,
            "people": (10, 24),
            "person_days": 120,
            "skills": ["厨房建设", "食品安全", "采购"],
            "criteria": ["每日可供应 100 人三餐", "食材储存和清洗动线可用", "食品安全责任人明确"],
        },
        {
            "code": "B2",
            "parent": "B0",
            "title": "搭建临时住宿和洗浴区",
            "node_type": PlanNode.NodeType.WORK_PACKAGE,
            "status": PlanNode.Status.PLANNED,
            "duration": 6,
            "cost": 300000,
            "people": (12, 30),
            "person_days": 160,
            "criteria": ["提供 120 个临时床位", "完成基础洗浴和夜间照明", "消防通道明确"],
        },
        {
            "code": "B3",
            "parent": "B0",
            "title": "临时供水与净水系统",
            "node_type": PlanNode.NodeType.WORK_PACKAGE,
            "status": PlanNode.Status.PLANNED,
            "duration": 4,
            "cost": 180000,
            "people": (6, 14),
            "person_days": 56,
            "skills": ["给排水", "卫生"],
            "criteria": ["每日可提供 120 人基础用水", "净水和污水风险可监控"],
        },
        {
            "code": "B4",
            "parent": "B0",
            "title": "临时供电和安全照明",
            "node_type": PlanNode.NodeType.WORK_PACKAGE,
            "status": PlanNode.Status.PLANNED,
            "duration": 4,
            "cost": 260000,
            "people": (6, 12),
            "person_days": 50,
            "skills": ["电工", "安全"],
            "criteria": ["关键区域持续供电", "夜间安全照明覆盖主通道"],
        },
        {
            "code": "B5",
            "parent": "B0",
            "title": "公共卫生和垃圾处理制度",
            "node_type": PlanNode.NodeType.OPERATIONS,
            "status": PlanNode.Status.PLANNED,
            "duration": 5,
            "cost": 90000,
            "people": (10, 25),
            "person_days": 90,
            "criteria": ["建立公共清洁排班", "垃圾分类和转运可执行", "卫生事件有上报路径"],
        },
        {
            "code": "B6",
            "parent": "B0",
            "title": "仓储一区和工具库",
            "node_type": PlanNode.NodeType.WORK_PACKAGE,
            "status": PlanNode.Status.PLANNED,
            "duration": 6,
            "cost": 280000,
            "people": (8, 20),
            "person_days": 120,
            "criteria": ["建立 300 立方米基础仓储", "工具借还登记可用", "高风险物资单独保管"],
        },
        {
            "code": "C0",
            "title": "第一轮扩容和新成员接纳",
            "node_type": PlanNode.NodeType.STAGE,
            "status": PlanNode.Status.PLANNED,
            "duration": 45,
            "cost": 9000000,
            "people": (60, 180),
            "person_days": 4200,
            "criteria": ["完成第一批正式设施扩建", "容量评估允许新增成员", "完成第一批新成员接纳"],
        },
        {
            "code": "C1",
            "parent": "C0",
            "title": "公共食堂一期",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 14,
            "cost": 1200000,
            "people": (20, 50),
            "person_days": 420,
            "is_expandable": True,
            "criteria": ["供餐能力达到 300 人/日", "厨房、仓储、洗消区域分离", "食堂排班制度可执行"],
        },
        {
            "code": "C2",
            "parent": "C0",
            "title": "正式住房一期",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 24,
            "cost": 3200000,
            "people": (30, 80),
            "person_days": 1200,
            "is_expandable": True,
            "criteria": ["新增 150 个正式床位", "基础消防和隐私隔断合格", "住宿管理制度可执行"],
        },
        {
            "code": "C3",
            "parent": "C0",
            "title": "光伏一期 0.5MW",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 21,
            "cost": 2500000,
            "people": (12, 36),
            "person_days": 450,
            "is_expandable": True,
            "criteria": [
                "装机规模达到 0.5MW",
                "关键生活负载具备白天供电保障",
                "取得结构、设计、并网、施工、验收归档责任文件",
                "运维责任边界明确",
            ],
            "metadata": {
                "required_responsibility_closures": photovoltaic_responsibility_closure_requirements(),
                "responsibility_documents": [],
                "professional_responsibility_boundary": "社区做业主方管理和低风险辅助，关键工程责任由可追责主体承担。",
            },
        },
        {
            "code": "C4",
            "parent": "C0",
            "title": "仓储空间一期扩容",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 12,
            "cost": 800000,
            "people": (15, 40),
            "person_days": 300,
            "criteria": ["新增 800 立方米仓储", "食品、工具、药品分区", "库存盘点制度上线"],
        },
        {
            "code": "C5",
            "parent": "C0",
            "title": "办公和会议空间一期",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 10,
            "cost": 600000,
            "people": (12, 30),
            "person_days": 240,
            "criteria": ["提供 500 平方米办公会议空间", "运营、治理、培训可分区进行"],
        },
        {
            "code": "C6",
            "parent": "C0",
            "title": "第一批新成员接纳",
            "node_type": PlanNode.NodeType.CAPACITY_GATE,
            "status": PlanNode.Status.PLANNED,
            "duration": 5,
            "cost": 300000,
            "people": (20, 60),
            "person_days": 200,
            "criteria": ["容量评估通过", "接纳流程和培训完成", "新增成员不压垮食宿水电安全线"],
        },
        {
            "code": "D0",
            "title": "长期空间和对外服务扩张",
            "node_type": PlanNode.NodeType.STAGE,
            "status": PlanNode.Status.PLANNED,
            "duration": 180,
            "cost": 50000000,
            "people": (100, 400),
            "person_days": 24000,
            "criteria": ["据点具备稳定扩张能力", "生产、生活、接待、治理空间成体系"],
        },
        {
            "code": "D1",
            "parent": "D0",
            "title": "光伏二期 2MW 和储能配套",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 60,
            "cost": 12000000,
            "people": (25, 80),
            "person_days": 2200,
            "skills": ["光伏", "储能", "电气"],
            "is_expandable": True,
            "criteria": ["累计新增 2MW 光伏", "关键生产和生活负载有储能保障"],
        },
        {
            "code": "D2",
            "parent": "D0",
            "title": "正式住房二期",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 75,
            "cost": 18000000,
            "people": (60, 180),
            "person_days": 6000,
            "is_expandable": True,
            "criteria": ["新增 400 个正式床位", "形成家庭、单人、短住多类型住房"],
        },
        {
            "code": "D3",
            "parent": "D0",
            "title": "娱乐和公共活动空间",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 35,
            "cost": 3500000,
            "people": (20, 70),
            "person_days": 1200,
            "criteria": ["提供 800 平方米活动空间", "支持文体、培训、公共讨论和儿童活动"],
        },
        {
            "code": "D4",
            "parent": "D0",
            "title": "民宿和旅馆一期",
            "node_type": PlanNode.NodeType.EXPANSION,
            "status": PlanNode.Status.PLANNED,
            "duration": 60,
            "cost": 9000000,
            "people": (30, 120),
            "person_days": 3000,
            "criteria": ["形成 30 间对外接待房", "建立访客登记、价格、清洁和安全规则"],
        },
        {
            "code": "D5",
            "parent": "D0",
            "title": "治理、运营和公共服务升级",
            "node_type": PlanNode.NodeType.GOVERNANCE,
            "status": PlanNode.Status.PLANNED,
            "duration": 30,
            "cost": 1000000,
            "people": (20, 80),
            "person_days": 1000,
            "criteria": ["完成治理流程升级", "形成运营仪表盘", "建立接待、培训、争议和财务复盘机制"],
        },
    ]
    return plan_node_specs


def dependency_specs():
    dependency_specs = [
        ("A0", "R0", PlanDependency.DependencyType.FINISH_TO_START, "人员和行前准备完成后才能集结抵达。"),
        ("M0", "A0", PlanDependency.DependencyType.FINISH_TO_START, "关键人员抵达后才能进行现场会议。"),
        ("B0", "M0", PlanDependency.DependencyType.GOVERNANCE_APPROVAL, "初步开荒必须基于会议确认的执行计划。"),
        ("C0", "B0", PlanDependency.DependencyType.CAPACITY_GATE, "基础生活能力达到安全线后才能接纳新成员。"),
        ("D0", "C0", PlanDependency.DependencyType.CAPACITY_GATE, "完成第一轮扩容后进入长期空间建设。"),
        ("C1", "B1", PlanDependency.DependencyType.FINISH_TO_START, "临时食堂运行稳定后再建设正式食堂一期。"),
        ("C2", "B2", PlanDependency.DependencyType.FINISH_TO_START, "临时住宿经验用于正式住房设计。"),
        ("C3", "B4", PlanDependency.DependencyType.FINISH_TO_START, "临时供电确认负载后再上光伏一期。"),
        ("C6", "C1", PlanDependency.DependencyType.CAPACITY_GATE, "供餐能力达标是第一批新成员接纳前置条件。"),
        ("C6", "C2", PlanDependency.DependencyType.CAPACITY_GATE, "正式床位达标是第一批新成员接纳前置条件。"),
        ("D1", "C3", PlanDependency.DependencyType.FINISH_TO_START, "一期光伏运维稳定后才能扩到二期。"),
        ("D4", "D3", PlanDependency.DependencyType.FINISH_TO_START, "公共活动和接待秩序稳定后再建设民宿旅馆。"),
    ]
    return dependency_specs


def capacity_impact_specs():
    capacity_impacts = [
        ("B1", PlanCapacityImpact.ImpactType.CANTEEN_MEALS_PER_DAY, "300", "餐/日", "临时食堂支持 100 人三餐。"),
        ("B2", PlanCapacityImpact.ImpactType.BED_SLOTS, "120", "床位", "临时住宿提供 120 个床位。"),
        ("B4", PlanCapacityImpact.ImpactType.ELECTRICITY_KWH_PER_DAY, "1200", "kWh/日", "临时供电覆盖关键生活负载。"),
        ("B6", PlanCapacityImpact.ImpactType.STORAGE_CUBIC_METER, "300", "立方米", "建立仓储一区。"),
        ("C1", PlanCapacityImpact.ImpactType.CANTEEN_MEALS_PER_DAY, "600", "餐/日", "正式食堂一期支持 300 人每日两餐以上。"),
        ("C2", PlanCapacityImpact.ImpactType.BED_SLOTS, "150", "床位", "正式住房一期新增床位。"),
        ("C3", PlanCapacityImpact.ImpactType.PV_MW, "0.500", "MW", "光伏一期装机。"),
        ("C4", PlanCapacityImpact.ImpactType.STORAGE_CUBIC_METER, "800", "立方米", "仓储空间一期扩容。"),
        ("C5", PlanCapacityImpact.ImpactType.OFFICE_SQUARE_METER, "500", "平方米", "办公和会议空间一期。"),
        ("C6", PlanCapacityImpact.ImpactType.MEMBER_CAPACITY, "120", "人", "第一批新成员接纳容量。"),
        ("D1", PlanCapacityImpact.ImpactType.PV_MW, "2.000", "MW", "光伏二期和储能配套。"),
        ("D2", PlanCapacityImpact.ImpactType.BED_SLOTS, "400", "床位", "正式住房二期。"),
        ("D3", PlanCapacityImpact.ImpactType.RECREATION_SQUARE_METER, "800", "平方米", "娱乐和公共活动空间。"),
        ("D4", PlanCapacityImpact.ImpactType.HOSPITALITY_ROOMS, "30", "间", "民宿和旅馆一期。"),
    ]
    return capacity_impacts
