"""URL routes for the workspace."""

from django.urls import path
from worlds.routing import world_scoped_view

from . import credit_views, deliberator_exam_views, task_views, views, finance_views, finance_role_views, inventory_views, procurement_views, proposal_views, risk_views


urlpatterns = [
    path("", world_scoped_view(views.workspace_page), name="workspace-page"),
    path("deliberator-exam/", world_scoped_view(deliberator_exam_views.deliberator_exam_home), name="workspace-deliberator-exam"),
    path("deliberator-exam/configuration/", world_scoped_view(deliberator_exam_views.deliberator_exam_configuration), name="workspace-deliberator-exam-configuration"),
    path("deliberator-exam/<str:attempt_id>/", world_scoped_view(deliberator_exam_views.deliberator_exam_attempt), name="workspace-deliberator-exam-attempt"),
    path(
        "credits/transfer/",
        world_scoped_view(credit_views.credit_transfer_page),
        name="workspace-credits-transfer",
    ),
    path(
        "credits/redemption/",
        world_scoped_view(credit_views.redemption_orders_page),
        name="workspace-credits-redemption",
    ),
    path(
        "credits/redemption/review/",
        world_scoped_view(credit_views.redemption_review_page),
        name="workspace-credits-review",
    ),
    path(
        "credits/merchant-settlements/",
        world_scoped_view(credit_views.merchant_settlements_page),
        name="workspace-credits-settlements",
    ),
    path(
        "credits/budgets/",
        world_scoped_view(credit_views.budgets_page),
        name="workspace-credits-budgets",
    ),
    path(
        "tasks/",
        world_scoped_view(views.workspace_tasks),
        name="workspace-tasks",
    ),
    path(
        "tasks/<str:task_id>/claim/",
        world_scoped_view(views.workspace_claim_task),
        name="workspace-claim-task",
    ),
    path(
        "tasks/<str:task_id>/submit-labor/",
        world_scoped_view(views.workspace_submit_labor),
        name="workspace-submit-labor",
    ),
    path(
        "tasks/new/",
        world_scoped_view(task_views.task_create_page),
        name="workspace-tasks-manage",
    ),
    path(
        "tasks/<str:task_id>/publish/",
        world_scoped_view(task_views.task_publish_page),
        name="workspace-tasks-publish",
    ),
    path(
        "tasks/review/",
        world_scoped_view(task_views.task_review_page),
        name="workspace-tasks-review",
    ),
    path(
        "tasks/<str:task_id>/",
        world_scoped_view(views.workspace_task_detail),
        name="workspace-task-detail",
    ),
    path(
        "applications/",
        world_scoped_view(views.workspace_applications_review),
        name="workspace-applications-review",
    ),
    path(
        "applications/<str:application_id>/",
        world_scoped_view(views.workspace_application_detail),
        name="workspace-application-detail",
    ),
    path(
        "apply/",
        world_scoped_view(views.workspace_member_application),
        name="workspace-member-application",
    ),
    path(
        "profile/",
        world_scoped_view(views.workspace_public_profile_page),
        name="workspace-public-profile",
    ),
    path(
        "profile/update/",
        world_scoped_view(views.workspace_public_profile_update),
        name="workspace-public-profile-update",
    ),
    path(
        "profile/avatar/upload/",
        world_scoped_view(views.workspace_avatar_upload),
        name="workspace-avatar-upload",
    ),
    path(
        "profile/avatar/remove/",
        world_scoped_view(views.workspace_avatar_remove),
        name="workspace-avatar-remove",
    ),
    path(
        "finance/claims/",
        world_scoped_view(finance_views.finance_claims_list),
        name="workspace-finance-list",
    ),
    path(
        "finance/reviewer-appointments/",
        world_scoped_view(finance_role_views.finance_reviewer_appointments),
        name="workspace-finance-reviewer-appointments",
    ),
    path(
        "finance/claims/new/",
        world_scoped_view(finance_views.finance_claim_form),
        name="workspace-finance-new",
    ),
    path(
        "finance/claims/<str:claim_id>/",
        world_scoped_view(finance_views.finance_claim_detail),
        name="workspace-finance-detail",
    ),
    path(
        "finance/claims/<str:claim_id>/review/",
        world_scoped_view(finance_views.finance_claim_review),
        name="workspace-finance-review",
    ),
    path(
        "finance/claims/<str:claim_id>/pay/",
        world_scoped_view(finance_views.finance_claim_pay),
        name="workspace-finance-pay",
    ),
    path(
        "finance/claims/<str:claim_id>/withdraw/",
        world_scoped_view(finance_views.finance_claim_withdraw),
        name="workspace-finance-withdraw",
    ),
    path(
        "finance/claims/<str:claim_id>/attachments/<str:attachment_id>/",
        world_scoped_view(finance_views.finance_attachment_download),
        name="workspace-finance-attachment",
    ),
    path(
        "finance/claims/<str:claim_id>/attachments/publish/",
        world_scoped_view(finance_views.finance_attachment_publish),
        name="workspace-finance-attachment-publish",
    ),
    path(
        "recruitment/",
        world_scoped_view(views.workspace_recruitment),
        name="workspace-recruitment",
    ),
    path(
        "inventory/",
        world_scoped_view(inventory_views.inventory_list),
        name="workspace-inventory",
    ),
    path(
        "inventory/<str:resource_id>/adjust/",
        world_scoped_view(inventory_views.inventory_adjust),
        name="workspace-inventory-adjust",
    ),
    path(
        "inventory/new/",
        world_scoped_view(inventory_views.inventory_new),
        name="workspace-inventory-new",
    ),
    path(
        "inventory/<str:resource_id>/edit/",
        world_scoped_view(inventory_views.inventory_edit),
        name="workspace-inventory-edit",
    ),
    path(
        "proposals/",
        world_scoped_view(proposal_views.proposal_list),
        name="workspace-approval-proposals",
    ),
    path(
        "approval-proposals/<str:proposal_id>/approve/",
        world_scoped_view(proposal_views.approval_proposal_approve),
        name="workspace-approval-proposal-approve",
    ),
    path(
        "approval-proposals/<str:proposal_id>/reject/",
        world_scoped_view(proposal_views.approval_proposal_reject),
        name="workspace-approval-proposal-reject",
    ),
    path(
        "approval-proposals/<str:proposal_id>/execute/",
        world_scoped_view(proposal_views.approval_proposal_execute),
        name="workspace-approval-proposal-execute",
    ),
    path(
        "procurement/",
        world_scoped_view(procurement_views.procurement_list),
        name="workspace-procurement",
    ),
    path(
        "procurement/<str:quote_id>/create-proposal/",
        world_scoped_view(procurement_views.procurement_create_proposal),
        name="workspace-procurement-create-proposal",
    ),
    path(
        "procurement/<str:quote_id>/receipt/",
        world_scoped_view(procurement_views.procurement_receipt),
        name="workspace-procurement-receipt",
    ),
    path(
        "procurement/<str:quote_id>/complete/",
        world_scoped_view(procurement_views.procurement_complete),
        name="workspace-procurement-complete",
    ),
    path(
        "procurement/challenges/",
        world_scoped_view(procurement_views.procurement_challenge_list),
        name="workspace-procurement-challenges",
    ),
    path(
        "procurement/challenges/<str:challenge_id>/review/",
        world_scoped_view(procurement_views.procurement_challenge_review),
        name="workspace-procurement-challenge-review",
    ),
    path("risks/", world_scoped_view(risk_views.risk_list), name="workspace-risks"),
    path("risks/<str:alert_id>/acknowledge/", world_scoped_view(risk_views.risk_ack), name="workspace-risk-acknowledge"),
    path("risks/<str:alert_id>/resolve/", world_scoped_view(risk_views.risk_resolve), name="workspace-risk-resolve"),
    path("risk-rules/", world_scoped_view(risk_views.risk_rules_list), name="workspace-risk-rules"),
    path("risk-rules/<str:rule_id>/update/", world_scoped_view(risk_views.risk_rule_update), name="workspace-risk-rule-update"),
]
